// Package store persists MockVision's state in an embedded SQLite database.
//
// It follows the persistence rules of the architecture: WAL, foreign keys on,
// a 5 s busy timeout and a single write connection, with migrations embedded
// in the binary. Typed queries are generated by sqlc into the db subpackage.
package store

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io/fs"
	"net/url"
	"runtime"
	"sync/atomic"
	"time"

	"github.com/pressly/goose/v3"
	"modernc.org/sqlite"
	sqlite3 "modernc.org/sqlite/lib"

	"github.com/corticoide/mockvision/backend/internal/domain"
	"github.com/corticoide/mockvision/backend/internal/store/db"
	"github.com/corticoide/mockvision/database"
)

// Store gives access to the database through a pool of readers and a single
// writer, as SQLite allows only one writer at a time.
type Store struct {
	reader *sql.DB
	writer *sql.DB
	r      *db.Queries
	w      *db.Queries
	stats  *writeStats
}

// Stats counts write activity. The event log is the heaviest writer and the
// database may live on an SD card, so writes are measured from day one.
type Stats struct {
	WriteStatements uint64 `json:"write_statements"`
	WriteTxs        uint64 `json:"write_transactions"`
}

type writeStats struct {
	statements atomic.Uint64
	txs        atomic.Uint64
}

// Open opens (creating if needed) the database file and applies migrations.
func Open(ctx context.Context, path string) (*Store, error) {
	writerDSN, readerDSN := dsn(path)
	writer, err := sql.Open("sqlite", writerDSN)
	if err != nil {
		return nil, err
	}
	writer.SetMaxOpenConns(1)
	writer.SetMaxIdleConns(1)
	writer.SetConnMaxLifetime(0)

	reader, err := sql.Open("sqlite", readerDSN)
	if err != nil {
		writer.Close()
		return nil, err
	}
	n := runtime.NumCPU()
	if n < 2 {
		n = 2
	}
	reader.SetMaxOpenConns(n)

	s := &Store{reader: reader, writer: writer, stats: &writeStats{}}
	if err := s.migrate(ctx); err != nil {
		s.Close()
		return nil, err
	}
	s.r = db.New(reader)
	s.w = db.New(&countingDB{DBTX: writer, stats: s.stats})
	return s, nil
}

func dsn(path string) (writer, reader string) {
	common := url.Values{}
	common.Add("_pragma", "busy_timeout(5000)")
	common.Add("_pragma", "foreign_keys(1)")
	common.Add("_pragma", "synchronous(NORMAL)")
	w := url.Values{}
	for k, v := range common {
		w[k] = append([]string(nil), v...)
	}
	w.Add("_pragma", "journal_mode(WAL)")
	w.Set("_txlock", "immediate")
	r := url.Values{}
	for k, v := range common {
		r[k] = append([]string(nil), v...)
	}
	r.Add("_pragma", "query_only(1)")
	return "file:" + path + "?" + w.Encode(), "file:" + path + "?" + r.Encode()
}

func (s *Store) migrate(ctx context.Context) error {
	migrations, err := fs.Sub(database.Migrations, "migrations")
	if err != nil {
		return err
	}
	provider, err := goose.NewProvider(goose.DialectSQLite3, s.writer, migrations)
	if err != nil {
		return fmt.Errorf("migrations: %w", err)
	}
	if _, err := provider.Up(ctx); err != nil {
		return fmt.Errorf("apply migrations: %w", err)
	}
	return nil
}

// Close closes both pools.
func (s *Store) Close() error {
	var errs []error
	if s.reader != nil {
		errs = append(errs, s.reader.Close())
	}
	if s.writer != nil {
		errs = append(errs, s.writer.Close())
	}
	return errors.Join(errs...)
}

// R returns queries bound to the reader pool.
func (s *Store) R() *db.Queries { return s.r }

// W returns queries bound to the single writer connection.
func (s *Store) W() *db.Queries { return s.w }

// Tx runs fn inside a write transaction (BEGIN IMMEDIATE).
func (s *Store) Tx(ctx context.Context, fn func(q *db.Queries) error) error {
	tx, err := s.writer.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	s.stats.txs.Add(1)
	q := db.New(&countingDB{DBTX: tx, stats: s.stats})
	if err := fn(q); err != nil {
		_ = tx.Rollback()
		return err
	}
	return tx.Commit()
}

// Stats returns write counters since startup.
func (s *Store) Stats() Stats {
	return Stats{WriteStatements: s.stats.statements.Load(), WriteTxs: s.stats.txs.Load()}
}

// countingDB counts statements that go through the writer.
type countingDB struct {
	db.DBTX
	stats *writeStats
}

func (c *countingDB) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	c.stats.statements.Add(1)
	return c.DBTX.ExecContext(ctx, query, args...)
}

// NotFound maps sql.ErrNoRows to domain.ErrNotFound.
func NotFound(err error) error {
	if errors.Is(err, sql.ErrNoRows) {
		return domain.ErrNotFound
	}
	return err
}

// IsUnique reports whether err is a UNIQUE or PRIMARY KEY violation.
func IsUnique(err error) bool {
	var se *sqlite.Error
	if !errors.As(err, &se) {
		return false
	}
	code := se.Code()
	return code == sqlite3.SQLITE_CONSTRAINT_UNIQUE || code == sqlite3.SQLITE_CONSTRAINT_PRIMARYKEY
}

// IsForeignKey reports whether err is a foreign key violation.
func IsForeignKey(err error) bool {
	var se *sqlite.Error
	if !errors.As(err, &se) {
		return false
	}
	return se.Code() == sqlite3.SQLITE_CONSTRAINT_FOREIGNKEY
}

// Millis converts a time to the storage representation.
func Millis(t time.Time) int64 {
	if t.IsZero() {
		return 0
	}
	return t.UnixMilli()
}

// Time converts the storage representation to a time.
func Time(ms int64) time.Time {
	if ms == 0 {
		return time.Time{}
	}
	return time.UnixMilli(ms).UTC()
}

// NullMillis converts an optional time.
func NullMillis(t time.Time) sql.NullInt64 {
	if t.IsZero() {
		return sql.NullInt64{}
	}
	return sql.NullInt64{Int64: t.UnixMilli(), Valid: true}
}

// NullTime converts an optional stored time.
func NullTime(v sql.NullInt64) time.Time {
	if !v.Valid {
		return time.Time{}
	}
	return Time(v.Int64)
}

// NullString converts an optional string.
func NullString(s string) sql.NullString {
	return sql.NullString{String: s, Valid: s != ""}
}

// Bool converts an INTEGER flag.
func Bool(v int64) bool { return v != 0 }

// Int converts a flag to INTEGER.
func Int(b bool) int64 {
	if b {
		return 1
	}
	return 0
}
