/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the first administrator (first run only) */
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user; 401 carries setup_required on a fresh node */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNodeMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchSettings"];
        trace?: never;
    };
    "/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a .mvpkg package or a loose profile.yaml (draft) */
        post: operations["importPackage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{vendor}/{model}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor: string;
                model: string;
                version: string;
            };
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{vendor}/{model}/versions/{version}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor: string;
                model: string;
                version: string;
                action: "archive" | "unarchive";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["profileAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCameras"];
        put?: never;
        post: operations["createCamera"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getCamera"];
        put?: never;
        post?: never;
        delete: operations["deleteCamera"];
        options?: never;
        head?: never;
        patch: operations["updateCamera"];
        trace?: never;
    };
    "/cameras/{id}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
                action: "start" | "stop" | "restart";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cameraAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getCameraStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getCameraConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchCameraConfig"];
        trace?: never;
    };
    "/cameras/{id}/metrics": {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getCameraMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual trigger; the camera serializes and delivers the event */
        post: operations["triggerEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssets"];
        put?: never;
        post: operations["uploadAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getAssetContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTargets"];
        put?: never;
        post: operations["createTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getTarget"];
        put?: never;
        post?: never;
        delete: operations["deleteTarget"];
        options?: never;
        head?: never;
        patch: operations["updateTarget"];
        trace?: never;
    };
    "/targets/{id}/actions/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            code?: string;
            errors?: {
                field: string;
                message: string;
            }[];
            report?: components["schemas"]["ImportReport"];
            setup_required?: boolean;
        };
        Credentials: {
            username: string;
            password: string;
        };
        Me: {
            user: {
                id: string;
                username: string;
                role: string;
            };
            /** Format: date-time */
            expires_at: string;
        };
        Interface: {
            name: string;
            mac: string;
            up: boolean;
            loopback: boolean;
            addrs: string[] | null;
            default: boolean;
            gateway?: string;
        };
        CameraCounts: {
            total: number;
            running: number;
            error: number;
        };
        Node: {
            version: string;
            /** @enum {string} */
            runtime: "netns" | "local";
            hostname: string;
            cpu_count: number;
            mem_total: number;
            default_interface: string;
            default_gateway: string;
            parent_interface: string;
            interfaces: components["schemas"]["Interface"][] | null;
            cameras: components["schemas"]["CameraCounts"];
            /** Format: date-time */
            started_at: string;
        };
        Settings: {
            max_cameras: number;
            max_ram_percent: number;
            max_cpu_percent: number;
            parent_interface: string;
            events_retention_days: number;
        };
        SettingsPatch: {
            max_cameras?: number;
            max_ram_percent?: number;
            max_cpu_percent?: number;
            parent_interface?: string;
            events_retention_days?: number;
        };
        NodeMetrics: {
            /** Format: date-time */
            at: string;
            cpu_percent: number;
            cpu_sustained_percent: number;
            mem_total: number;
            mem_used: number;
            cameras: {
                [key: string]: components["schemas"]["CameraMetrics"];
            };
            camera_counts: components["schemas"]["CameraCounts"];
            db: {
                write_statements: number;
                write_transactions: number;
            };
            limits: components["schemas"]["Settings"];
        };
        Profile: {
            id: string;
            profile_id: string;
            version: string;
            name: string;
            vendor: string;
            model: string;
            firmware: string[];
            /** @enum {string} */
            level: "draft" | "documented" | "captured" | "verified";
            signature_status: string;
            archived: boolean;
            camera_count: number;
            /** Format: date-time */
            created_at: string;
            coverage?: {
                [key: string]: string;
            };
        };
        ProfileStream: {
            name: string;
            codecs: string[];
            resolutions: string[];
            fps_min: number;
            fps_max: number;
            default: {
                codec: string;
                resolution: string;
                fps: number;
                bitrate: number;
                gop: number;
            };
        };
        ProfileDetail: components["schemas"]["Profile"] & {
            streams: components["schemas"]["ProfileStream"][];
            engines: {
                instance: string;
                engine: string;
                port?: number;
            }[];
            events: string[];
            factory_users: components["schemas"]["CameraUser"][];
            factory_ip?: string;
            params: components["schemas"]["Param"][];
        };
        ImportProblem: {
            step: string;
            /** @enum {string} */
            severity: "error" | "warning";
            file?: string;
            line?: number;
            pointer?: string;
            message: string;
        };
        ImportReport: {
            kind: string;
            id: string;
            version: string;
            sha256: string;
            signature: string;
            level?: string;
            coverage?: {
                [key: string]: string;
            };
            steps: {
                name: string;
                /** @enum {string} */
                status: "passed" | "failed" | "skipped";
                note?: string;
            }[];
            problems: components["schemas"]["ImportProblem"][];
        };
        ImportResult: {
            profile: components["schemas"]["Profile"];
            report: components["schemas"]["ImportReport"];
            created: boolean;
        };
        CameraUser: {
            username: string;
            role: string;
        };
        CameraStatus: {
            /** @enum {string} */
            state: "stopped" | "provisioning" | "starting" | "running" | "degraded" | "restarting" | "stopping" | "error";
            reason: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            last_heartbeat: string | null;
            netns?: string;
            pid?: number;
            retries: number;
        };
        Endpoint: {
            instance: string;
            engine: string;
            protocol: string;
            port: number;
            url: string;
        };
        Stream: {
            name: string;
            codec: string;
            resolution: string;
            fps: number;
            gop: number;
            bitrate: number;
            asset_id: string;
            rendition_id?: string;
            /** @enum {string} */
            rendition_status: "pending" | "ready" | "failed" | "missing";
            rendition_error?: string;
        };
        CameraMetrics: {
            /** Format: date-time */
            at: string;
            cpu_percent: number;
            rss_bytes: number;
            clients: number;
            bytes_in: number;
            bytes_out: number;
            requests: number;
        };
        Network: {
            mode: string;
            parent: string;
            mac: string;
            ip_mode: string;
            ip: string;
            netmask: string;
            prefix: number;
            gateway: string;
            dns: string[];
        };
        Camera: {
            id: string;
            name: string;
            profile: {
                id: string;
                version: string;
                name: string;
                vendor: string;
                model: string;
                level: string;
            };
            serial: string;
            /** @enum {string} */
            desired_state: "running" | "stopped";
            autostart: boolean;
            tags: string[];
            network: components["schemas"]["Network"];
            status: components["schemas"]["CameraStatus"];
            endpoints: components["schemas"]["Endpoint"][];
            streams: components["schemas"]["Stream"][];
            users: components["schemas"]["CameraUser"][];
            targets: {
                id: string;
                name: string;
                event_types: string[];
            }[];
            metrics: components["schemas"]["CameraMetrics"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateCamera: {
            name: string;
            profile_id: string;
            profile_version: string;
            network?: {
                parent?: string;
                mac?: string;
                vendor_oui?: boolean;
                ip?: string;
                netmask?: string;
                gateway?: string;
            };
            users?: {
                username: string;
                password: string;
                /** @enum {string} */
                role?: "admin" | "operator" | "viewer";
            }[];
            stream?: {
                asset_id?: string;
                resolution?: string;
                fps?: number;
            };
            target_ids?: string[];
            autostart?: boolean;
            start?: boolean;
            tags?: string[];
        };
        UpdateCamera: {
            name?: string;
            autostart?: boolean;
            tags?: string[];
            target_ids?: string[];
        };
        Param: {
            key: string;
            /** @enum {string} */
            type: "string" | "int" | "float" | "bool" | "enum";
            value: unknown;
            default: unknown;
            values?: unknown[];
            min?: number;
            max?: number;
            bind?: string;
            effective: boolean;
            description?: string;
            origin: string;
            /** Format: date-time */
            updated_at: string;
        };
        ParamList: {
            params: components["schemas"]["Param"][];
        };
        Asset: {
            id: string;
            filename: string;
            mime: string;
            width: number;
            height: number;
            size: number;
            sha256: string;
            builtin: boolean;
            camera_count: number;
            /** Format: date-time */
            created_at: string;
        };
        Target: {
            id: string;
            name: string;
            /** @enum {string} */
            type: "http";
            url: string;
            method: string;
            headers: {
                [key: string]: string;
            };
            username: string;
            has_password: boolean;
            enabled: boolean;
            camera_count: number;
            /** Format: date-time */
            created_at: string;
        };
        TargetInput: {
            name?: string;
            /** @enum {string} */
            type?: "http";
            url?: string;
            /** @enum {string} */
            method?: "GET" | "POST" | "PUT";
            headers?: {
                [key: string]: string;
            };
            username?: string;
            password?: string;
            enabled?: boolean;
        };
        TargetTest: {
            ok: boolean;
            http_status?: number;
            latency_ms: number;
            error?: string;
        };
        Trigger: {
            /** @example line_crossing */
            type: string;
            /** @enum {string} */
            direction?: "A->B" | "B->A" | "none";
            object?: {
                class: string;
                color?: string;
                confidence?: number;
            };
            plate?: {
                text: string;
                format?: string;
                color?: string;
            };
            speed?: {
                value: number;
                unit: string;
                limit?: number;
            };
            custom?: {
                [key: string]: unknown;
            };
        };
        Delivery: {
            id: string;
            event_id: string;
            target_id: string;
            target_name: string;
            attempt: number;
            /** Format: date-time */
            at: string;
            /** @enum {string} */
            status: "ok" | "retry" | "failed";
            http_status?: number;
            latency_ms: number;
            error?: string;
        };
        Event: {
            id: string;
            camera_id: string;
            camera_name: string;
            type: string;
            /** Format: date-time */
            at: string;
            data: {
                [key: string]: unknown;
            };
            deliveries: components["schemas"]["Delivery"][];
            /** @enum {string} */
            delivery_status: "ok" | "failed" | "pending" | "none";
            latency_ms: number | null;
        };
        EventPage: {
            items: components["schemas"]["Event"][];
            next_cursor?: string;
        };
    };
    responses: {
        /** @description Problem */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Created and logged in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getNode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
        };
    };
    getNodeMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeMetrics"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    patchSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    importPackage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Already installed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Installed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Profile"][];
                    };
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor: string;
                model: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    profileAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor: string;
                model: string;
                version: string;
                action: "archive" | "unarchive";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
        };
    };
    listCameras: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cameras */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Camera"][];
                    };
                };
            };
        };
    };
    createCamera: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCamera"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getCamera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Camera */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    deleteCamera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCamera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCamera"];
            };
        };
        responses: {
            /** @description Camera */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
        };
    };
    cameraAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
                action: "start" | "stop" | "restart";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    getCameraStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: components["schemas"]["CameraStatus"];
                        endpoints: components["schemas"]["Endpoint"][];
                        metrics: components["schemas"]["CameraMetrics"] | null;
                    };
                };
            };
        };
    };
    getCameraConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Parameters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParamList"];
                };
            };
        };
    };
    patchCameraConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    values: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Parameters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParamList"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    getCameraMetrics: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Samples */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        samples: components["schemas"]["CameraMetrics"][];
                    };
                };
            };
        };
    };
    getSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JPEG */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
        };
    };
    triggerEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Trigger"];
            };
        };
        responses: {
            /** @description Emitted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listAssets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Asset"][];
                    };
                };
            };
        };
    };
    uploadAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    deleteAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Problem"];
        };
    };
    getAssetContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
        };
    };
    listTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Targets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Target"][];
                    };
                };
            };
        };
    };
    createTarget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
        };
    };
    deleteTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Problem"];
        };
    };
    updateTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetInput"];
            };
        };
        responses: {
            /** @description Target */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
        };
    };
    testTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetTest"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                camera_id?: string;
                type?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
}
