/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the first administrator (first run only) */
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, and the token of a request made with one; 401 carries setup_required on a fresh node */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNodeMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Node samples of the last ten minutes, every 2 s */
        get: operations["getNodeHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchSettings"];
        trace?: never;
    };
    "/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a .mvpkg package or a loose profile.yaml (draft)
         * @description The import runs as a job. The call waits up to a minute for it and
         *     answers with the result; when the job is still queued or running it
         *     answers 202 with the job, to follow at /jobs/{id}.
         */
        post: operations["importPackage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{vendor}/{model}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor: string;
                model: string;
                version: string;
            };
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{vendor}/{model}/versions/{version}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor: string;
                model: string;
                version: string;
                action: "archive" | "unarchive";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["profileAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API tokens of the current user (panel session only) */
        get: operations["listTokens"];
        put?: never;
        /** Create an API token (panel session only); the secret is returned once */
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API token (panel session only) */
        delete: operations["revokeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Background jobs, newest first (D72, D74) */
        get: operations["listJobs"];
        put?: never;
        /** Start a job; for now renditions.prepare, which encodes what the cameras need */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        /** A job with its history */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
                action: "cancel" | "resume" | "answer";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a job, resume an interrupted one, or answer its question ({"answer":"<option id>"}) */
        post: operations["jobAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who changed what, when and from where (kept 90 days) */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCameras"];
        put?: never;
        post: operations["createCamera"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/actions/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start, stop, restart, clone or delete several cameras; each gets its own result */
        post: operations["bulkCameras"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getCamera"];
        put?: never;
        post?: never;
        delete: operations["deleteCamera"];
        options?: never;
        head?: never;
        patch: operations["updateCamera"];
        trace?: never;
    };
    "/cameras/{id}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
                action: "start" | "stop" | "restart";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cameraAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/actions/factory-reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Restores the camera to its profile (RN-10): parameters, accounts and protocols; with scope full, also the profile's factory address. The picture is kept. A running camera reboots. */
        post: operations["resetCamera"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/actions/clone": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Creates a camera with the same profile, parameters, accounts, protocols, picture and targets, with its own ID, serial, MAC and address. */
        post: operations["cloneCamera"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        /** @description Replaces the camera's accounts (RN-11: at least one admin). An empty password keeps the account's current one. Applied at once. */
        put: operations["setCameraUsers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/protocols": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        /** @description Enables, disables or moves protocols of the camera's profile (RN-04). A running camera applies them when it restarts (RN-09). */
        put: operations["setCameraProtocols"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/streams/{stream}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
                stream: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Changes the picture, resolution or frame rate of a stream. The stream is encoded again and a running camera switches to it without restarting. */
        patch: operations["updateCameraStream"];
        trace?: never;
    };
    "/cameras/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getCameraStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getCameraConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchCameraConfig"];
        trace?: never;
    };
    "/cameras/{id}/metrics": {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getCameraMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual trigger; the camera serializes and delivers the event */
        post: operations["triggerEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssets"];
        put?: never;
        post: operations["uploadAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getAssetContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTargets"];
        put?: never;
        post: operations["createTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getTarget"];
        put?: never;
        post?: never;
        delete: operations["deleteTarget"];
        options?: never;
        head?: never;
        patch: operations["updateTarget"];
        trace?: never;
    };
    "/targets/{id}/actions/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            code?: string;
            errors?: {
                field: string;
                message: string;
            }[];
            report?: components["schemas"]["ImportReport"];
            setup_required?: boolean;
        };
        Credentials: {
            username: string;
            password: string;
        };
        Me: {
            user: {
                id: string;
                username: string;
                role: string;
            };
            /**
             * Format: date-time
             * @description Null for a token that does not expire
             */
            expires_at: string | null;
            token?: {
                id: string;
                name: string;
                scopes: ("read" | "write")[];
            };
        };
        Interface: {
            name: string;
            mac: string;
            up: boolean;
            loopback: boolean;
            addrs: string[] | null;
            default: boolean;
            gateway?: string;
        };
        CameraCounts: {
            total: number;
            /** @description Running and degraded */
            running: number;
            error: number;
            by_state: {
                [key: string]: number;
            };
        };
        Node: {
            version: string;
            /** @enum {string} */
            runtime: "netns" | "local";
            hostname: string;
            cpu_count: number;
            mem_total: number;
            default_interface: string;
            default_gateway: string;
            parent_interface: string;
            interfaces: components["schemas"]["Interface"][] | null;
            cameras: components["schemas"]["CameraCounts"];
            /** @description Where the panel and the API listen (D63) */
            panel: {
                listen: string;
                all_interfaces: boolean;
                urls: string[];
            };
            /** Format: date-time */
            started_at: string;
        };
        Settings: {
            max_cameras: number;
            max_ram_percent: number;
            max_cpu_percent: number;
            parent_interface: string;
            events_retention_days: number;
            /** @description Jobs that run at once (D72) */
            max_jobs: number;
            /** @description Bound of each step of a job (D72) */
            job_step_timeout_seconds: number;
        };
        SettingsPatch: {
            max_cameras?: number;
            max_ram_percent?: number;
            max_cpu_percent?: number;
            parent_interface?: string;
            events_retention_days?: number;
            max_jobs?: number;
            job_step_timeout_seconds?: number;
        };
        NodeMetrics: {
            /** Format: date-time */
            at: string;
            cpu_percent: number;
            cpu_sustained_percent: number;
            mem_total: number;
            mem_used: number;
            /** @description Interface the cameras hang from */
            net_interface: string;
            /** @description Bytes per second received */
            net_rx_bps: number;
            /** @description Bytes per second sent */
            net_tx_bps: number;
            cameras: {
                [key: string]: components["schemas"]["CameraMetrics"];
            };
            camera_counts: components["schemas"]["CameraCounts"];
            db: {
                write_statements: number;
                write_transactions: number;
            };
            limits: components["schemas"]["Settings"];
        };
        NodeSample: {
            /** Format: date-time */
            at: string;
            cpu_percent: number;
            mem_total: number;
            mem_used: number;
            net_interface: string;
            net_rx_bps: number;
            net_tx_bps: number;
        };
        Token: {
            id: string;
            name: string;
            /** @description First characters of the secret */
            prefix: string;
            scopes: ("read" | "write")[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string | null;
            /** Format: date-time */
            last_used_at: string | null;
            last_used_ip: string;
            expired: boolean;
        };
        TokenInput: {
            name: string;
            /** @description write implies read; none means read */
            scopes?: ("read" | "write")[];
            /** @description Null for a token that lasts until revoked */
            expires_in_days?: number | null;
        };
        CreatedToken: {
            token: components["schemas"]["Token"];
            /** @description Shown only now; the node keeps its hash */
            secret: string;
        };
        AuditEntry: {
            id: string;
            /** Format: date-time */
            at: string;
            actor: {
                /** @enum {string} */
                type: "user" | "camera" | "system";
                id: string;
                name: string;
            };
            /** @enum {string} */
            origin: "panel" | "api" | "camera" | "system";
            origin_ip: string;
            token: {
                id: string;
                name: string;
            } | null;
            action: string;
            entity: {
                type: string;
                id: string;
                name: string;
            };
            diff: {
                [key: string]: unknown;
            };
        };
        AuditPage: {
            items: components["schemas"]["AuditEntry"][];
            next_cursor?: string;
        };
        BulkAction: {
            /** @enum {string} */
            action: "start" | "stop" | "restart" | "clone" | "delete";
            ids: string[];
            /** @description Start each copy (clone only) */
            start?: boolean;
        };
        BulkResult: {
            action: string;
            succeeded: number;
            failed: number;
            results: {
                id: string;
                ok: boolean;
                camera?: components["schemas"]["Camera"];
                error?: components["schemas"]["Problem"];
            }[];
        };
        Profile: {
            id: string;
            profile_id: string;
            version: string;
            name: string;
            vendor: string;
            model: string;
            firmware: string[];
            /** @enum {string} */
            level: "draft" | "documented" | "captured" | "verified";
            signature_status: string;
            archived: boolean;
            camera_count: number;
            /** Format: date-time */
            created_at: string;
            coverage?: {
                [key: string]: string;
            };
        };
        ProfileStream: {
            name: string;
            codecs: string[];
            resolutions: string[];
            fps_min: number;
            fps_max: number;
            default: {
                codec: string;
                resolution: string;
                fps: number;
                bitrate: number;
                gop: number;
            };
        };
        ProfileDetail: components["schemas"]["Profile"] & {
            streams: components["schemas"]["ProfileStream"][];
            engines: {
                instance: string;
                engine: string;
                port?: number;
            }[];
            events: string[];
            factory_users: components["schemas"]["CameraUser"][];
            factory_ip?: string;
            params: components["schemas"]["Param"][];
        };
        ImportProblem: {
            step: string;
            /** @enum {string} */
            severity: "error" | "warning";
            file?: string;
            line?: number;
            pointer?: string;
            message: string;
        };
        ImportReport: {
            kind: string;
            id: string;
            version: string;
            sha256: string;
            signature: string;
            level?: string;
            coverage?: {
                [key: string]: string;
            };
            steps: {
                name: string;
                /** @enum {string} */
                status: "passed" | "failed" | "skipped";
                note?: string;
            }[];
            problems: components["schemas"]["ImportProblem"][];
        };
        ImportResult: {
            profile: components["schemas"]["Profile"];
            report: components["schemas"]["ImportReport"];
            created: boolean;
            /** @description The import job */
            job_id?: string;
        };
        Job: {
            id: string;
            /** @enum {string} */
            type: "rendition" | "import" | "renditions.prepare";
            title: string;
            /** @enum {string} */
            status: "queued" | "running" | "waiting" | "completed" | "failed" | "canceled" | "interrupted";
            progress: number;
            step: string;
            /** @description The decision the job waits for; unanswered, it takes the default when it expires */
            question: null | components["schemas"]["JobQuestion"];
            result: {
                [key: string]: unknown;
            };
            error: string;
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            finished_at: string | null;
        };
        JobQuestion: {
            id: string;
            text: string;
            options: {
                id: string;
                label: string;
            }[];
            default: string;
            /** Format: date-time */
            expires_at: string;
        };
        JobEvent: {
            job_id: string;
            seq: number;
            /** Format: date-time */
            at: string;
            /** @enum {string} */
            kind: "status" | "step" | "log" | "question" | "answer";
            data: {
                [key: string]: unknown;
            };
        };
        JobDetail: components["schemas"]["Job"] & {
            events: components["schemas"]["JobEvent"][];
        };
        JobPage: {
            items: components["schemas"]["Job"][];
            next_cursor?: string;
        };
        JobInput: {
            /** @enum {string} */
            type: "renditions.prepare";
            params?: {
                /** @description Only the renditions of this image */
                asset_id?: string;
            };
        };
        CameraUser: {
            username: string;
            role: string;
        };
        CameraStatus: {
            /** @enum {string} */
            state: "stopped" | "provisioning" | "starting" | "running" | "degraded" | "restarting" | "stopping" | "error";
            reason: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            last_heartbeat: string | null;
            netns?: string;
            pid?: number;
            retries: number;
            /** @description Saved changes a running camera applies when it restarts (RN-09). */
            pending_restart: ("network" | "protocols")[];
        };
        Protocol: {
            instance: string;
            engine: string;
            /** @enum {string} */
            role: "server" | "client";
            enabled: boolean;
            port: number;
            default_port: number;
        };
        Endpoint: {
            instance: string;
            engine: string;
            protocol: string;
            port: number;
            url: string;
        };
        Stream: {
            name: string;
            codec: string;
            resolution: string;
            fps: number;
            gop: number;
            bitrate: number;
            asset_id: string;
            rendition_id?: string;
            /** @enum {string} */
            rendition_status: "pending" | "ready" | "failed" | "missing";
            rendition_error?: string;
        };
        CameraMetrics: {
            /** Format: date-time */
            at: string;
            cpu_percent: number;
            rss_bytes: number;
            clients: number;
            bytes_in: number;
            bytes_out: number;
            requests: number;
        };
        Network: {
            mode: string;
            parent: string;
            mac: string;
            ip_mode: string;
            ip: string;
            netmask: string;
            prefix: number;
            gateway: string;
            dns: string[];
        };
        Camera: {
            id: string;
            name: string;
            profile: {
                id: string;
                version: string;
                name: string;
                vendor: string;
                model: string;
                level: string;
            };
            serial: string;
            /** @enum {string} */
            desired_state: "running" | "stopped";
            autostart: boolean;
            tags: string[];
            network: components["schemas"]["Network"];
            status: components["schemas"]["CameraStatus"];
            endpoints: components["schemas"]["Endpoint"][];
            protocols: components["schemas"]["Protocol"][];
            streams: components["schemas"]["Stream"][];
            users: components["schemas"]["CameraUser"][];
            targets: {
                id: string;
                name: string;
                event_types: string[];
            }[];
            metrics: components["schemas"]["CameraMetrics"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateCamera: {
            name: string;
            profile_id: string;
            profile_version: string;
            network?: components["schemas"]["NetworkInput"];
            users?: components["schemas"]["CameraUserInput"][];
            stream?: {
                asset_id?: string;
                resolution?: string;
                fps?: number;
            };
            target_ids?: string[];
            autostart?: boolean;
            start?: boolean;
            tags?: string[];
        };
        UpdateCamera: {
            name?: string;
            autostart?: boolean;
            tags?: string[];
            target_ids?: string[];
            /** @description The whole network identity; a running camera applies it when it restarts (RN-09). */
            network?: components["schemas"]["NetworkInput"];
        };
        /** @description Empty fields take the node's defaults. When editing, an empty MAC keeps the current one and default_mac goes back to the one derived from the camera ID. No DNS servers means the node's. */
        NetworkInput: {
            parent?: string;
            mac?: string;
            default_mac?: boolean;
            vendor_oui?: boolean;
            ip?: string;
            netmask?: string;
            gateway?: string;
            dns?: string[];
        };
        CameraUserInput: {
            username: string;
            /** @description Required for a new account; empty keeps the current one. */
            password?: string;
            /** @enum {string} */
            role?: "admin" | "operator" | "viewer";
        };
        CloneCamera: {
            name: string;
            network?: components["schemas"]["NetworkInput"];
            start?: boolean;
        };
        Param: {
            key: string;
            /** @enum {string} */
            type: "string" | "int" | "float" | "bool" | "enum";
            value: unknown;
            default: unknown;
            values?: unknown[];
            min?: number;
            max?: number;
            bind?: string;
            effective: boolean;
            description?: string;
            origin: string;
            /** Format: date-time */
            updated_at: string;
        };
        ParamList: {
            params: components["schemas"]["Param"][];
        };
        Asset: {
            id: string;
            filename: string;
            mime: string;
            width: number;
            height: number;
            size: number;
            sha256: string;
            builtin: boolean;
            camera_count: number;
            /** Format: date-time */
            created_at: string;
        };
        Target: {
            id: string;
            name: string;
            /** @enum {string} */
            type: "http";
            url: string;
            method: string;
            headers: {
                [key: string]: string;
            };
            username: string;
            has_password: boolean;
            enabled: boolean;
            camera_count: number;
            /** Format: date-time */
            created_at: string;
        };
        TargetInput: {
            name?: string;
            /** @enum {string} */
            type?: "http";
            url?: string;
            /** @enum {string} */
            method?: "GET" | "POST" | "PUT";
            headers?: {
                [key: string]: string;
            };
            username?: string;
            password?: string;
            enabled?: boolean;
        };
        TargetTest: {
            ok: boolean;
            http_status?: number;
            latency_ms: number;
            error?: string;
        };
        Trigger: {
            /** @example line_crossing */
            type: string;
            /** @enum {string} */
            direction?: "A->B" | "B->A" | "none";
            object?: {
                class: string;
                color?: string;
                confidence?: number;
            };
            plate?: {
                text: string;
                format?: string;
                color?: string;
            };
            speed?: {
                value: number;
                unit: string;
                limit?: number;
            };
            custom?: {
                [key: string]: unknown;
            };
        };
        Delivery: {
            id: string;
            event_id: string;
            target_id: string;
            target_name: string;
            attempt: number;
            /** Format: date-time */
            at: string;
            /** @enum {string} */
            status: "ok" | "retry" | "failed";
            http_status?: number;
            latency_ms: number;
            error?: string;
        };
        Event: {
            id: string;
            camera_id: string;
            camera_name: string;
            type: string;
            /** Format: date-time */
            at: string;
            data: {
                [key: string]: unknown;
            };
            deliveries: components["schemas"]["Delivery"][];
            /** @enum {string} */
            delivery_status: "ok" | "failed" | "pending" | "none";
            latency_ms: number | null;
        };
        EventPage: {
            items: components["schemas"]["Event"][];
            next_cursor?: string;
        };
    };
    responses: {
        /** @description Problem */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Created and logged in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getNode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
        };
    };
    getNodeMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeMetrics"];
                };
            };
        };
    };
    getNodeHistory: {
        parameters: {
            query?: {
                /** @description Unix milliseconds or RFC 3339 */
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Samples, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        samples: components["schemas"]["NodeSample"][];
                    };
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    patchSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    importPackage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Already installed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Installed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description The import goes on as a job */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job: components["schemas"]["Job"];
                    };
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Profile"][];
                    };
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor: string;
                model: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    profileAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor: string;
                model: string;
                version: string;
                action: "archive" | "unarchive";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Token"][];
                    };
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedToken"];
                };
            };
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listJobs: {
        parameters: {
            query?: {
                /** @description A status */
                status?: string;
                type?: "rendition" | "import" | "renditions.prepare";
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobInput"];
            };
        };
        responses: {
            /** @description Queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    jobAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
                action: "cancel" | "resume" | "answer";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    answer?: string;
                };
            };
        };
        responses: {
            /** @description Job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                origin?: "panel" | "api" | "camera" | "system";
                entity_type?: string;
                entity_id?: string;
                token_id?: string;
                /** @description Exact action or prefix */
                action?: string;
                /** @description Unix milliseconds or RFC 3339 */
                since?: string;
                /** @description Unix milliseconds or RFC 3339 */
                until?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            400: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listCameras: {
        parameters: {
            query?: {
                /** @description Text in the name */
                q?: string;
                state?: string;
                /** @description Profile ID or ID@version */
                profile?: string;
                tag?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cameras */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Camera"][];
                    };
                };
            };
        };
    };
    createCamera: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCamera"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    bulkCameras: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkAction"];
            };
        };
        responses: {
            /** @description Results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    getCamera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Camera */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    deleteCamera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCamera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCamera"];
            };
        };
        responses: {
            /** @description Camera */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
        };
    };
    cameraAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
                action: "start" | "stop" | "restart";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    resetCamera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    scope: "settings" | "full";
                };
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    cloneCamera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloneCamera"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    setCameraUsers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    users: components["schemas"]["CameraUserInput"][];
                };
            };
        };
        responses: {
            /** @description Camera */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    setCameraProtocols: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    protocols: {
                        instance: string;
                        enabled?: boolean;
                        port?: number;
                    }[];
                };
            };
        };
        responses: {
            /** @description Camera */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    updateCameraStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
                stream: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    asset_id?: string;
                    resolution?: string;
                    fps?: number;
                };
            };
        };
        responses: {
            /** @description Camera */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getCameraStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: components["schemas"]["CameraStatus"];
                        endpoints: components["schemas"]["Endpoint"][];
                        metrics: components["schemas"]["CameraMetrics"] | null;
                    };
                };
            };
        };
    };
    getCameraConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Parameters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParamList"];
                };
            };
        };
    };
    patchCameraConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    values: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Parameters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParamList"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    getCameraMetrics: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Samples */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        samples: components["schemas"]["CameraMetrics"][];
                    };
                };
            };
        };
    };
    getSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JPEG */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
        };
    };
    triggerEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Trigger"];
            };
        };
        responses: {
            /** @description Emitted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listAssets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Asset"][];
                    };
                };
            };
        };
    };
    uploadAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    deleteAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Problem"];
        };
    };
    getAssetContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
        };
    };
    listTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Targets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Target"][];
                    };
                };
            };
        };
    };
    createTarget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
        };
    };
    deleteTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Problem"];
        };
    };
    updateTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetInput"];
            };
        };
        responses: {
            /** @description Target */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
        };
    };
    testTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetTest"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                camera_id?: string;
                type?: string;
                /** @description Only events a target gave up on */
                delivery?: "failed";
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
}
