// MockVision engine contract, version 1, for external plugins.
//
// A plugin is an executable inside a .mvpkg package. The camera process
// launches it sandboxed, with its sockets already open, and talks to it over
// gRPC on inherited Unix sockets: the plugin serves Engine on descriptor 3,
// the camera serves Host on descriptor 4, and the engine's sockets follow
// from descriptor 5, as StartRequest.socket_fds names them. Host is
// limited to the permissions the user approved (net.listen, net.connect,
// accounts.read, state.read, state.write, events.emit, events.deliver,
// media.read, sd).
//
// Built-in engines implement the same contract in-process through the Go
// interfaces in sdk/engine; this file mirrors them for other languages.
// JSON payloads (config, values, events) are carried as bytes to keep the
// contract stable while profile schemas evolve.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: sdk/proto/mockvision/engine/v1/engine.proto

package enginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Engine_Describe_FullMethodName = "/mockvision.engine.v1.Engine/Describe"
	Engine_Validate_FullMethodName = "/mockvision.engine.v1.Engine/Validate"
	Engine_Start_FullMethodName    = "/mockvision.engine.v1.Engine/Start"
	Engine_Reload_FullMethodName   = "/mockvision.engine.v1.Engine/Reload"
	Engine_Health_FullMethodName   = "/mockvision.engine.v1.Engine/Health"
	Engine_Stop_FullMethodName     = "/mockvision.engine.v1.Engine/Stop"
)

// EngineClient is the client API for Engine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EngineClient interface {
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*Descriptor, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type engineClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineClient(cc grpc.ClientConnInterface) EngineClient {
	return &engineClient{cc}
}

func (c *engineClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*Descriptor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Descriptor)
	err := c.cc.Invoke(ctx, Engine_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, Engine_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, Engine_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadResponse)
	err := c.cc.Invoke(ctx, Engine_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Engine_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, Engine_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServer is the server API for Engine service.
// All implementations must embed UnimplementedEngineServer
// for forward compatibility.
type EngineServer interface {
	Describe(context.Context, *DescribeRequest) (*Descriptor, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Reload(context.Context, *ReloadRequest) (*ReloadResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedEngineServer()
}

// UnimplementedEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineServer struct{}

func (UnimplementedEngineServer) Describe(context.Context, *DescribeRequest) (*Descriptor, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedEngineServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedEngineServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedEngineServer) Reload(context.Context, *ReloadRequest) (*ReloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedEngineServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedEngineServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedEngineServer) mustEmbedUnimplementedEngineServer() {}
func (UnimplementedEngineServer) testEmbeddedByValue()                {}

// UnsafeEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServer will
// result in compilation errors.
type UnsafeEngineServer interface {
	mustEmbedUnimplementedEngineServer()
}

func RegisterEngineServer(s grpc.ServiceRegistrar, srv EngineServer) {
	// If the following call panics, it indicates UnimplementedEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Engine_ServiceDesc, srv)
}

func _Engine_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Engine_ServiceDesc is the grpc.ServiceDesc for Engine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Engine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mockvision.engine.v1.Engine",
	HandlerType: (*EngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Engine_Describe_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Engine_Validate_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Engine_Start_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _Engine_Reload_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Engine_Health_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Engine_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk/proto/mockvision/engine/v1/engine.proto",
}

const (
	Host_AccountsList_FullMethodName   = "/mockvision.engine.v1.Host/AccountsList"
	Host_StateGet_FullMethodName       = "/mockvision.engine.v1.Host/StateGet"
	Host_StateList_FullMethodName      = "/mockvision.engine.v1.Host/StateList"
	Host_StateSet_FullMethodName       = "/mockvision.engine.v1.Host/StateSet"
	Host_StateCanon_FullMethodName     = "/mockvision.engine.v1.Host/StateCanon"
	Host_StateWatch_FullMethodName     = "/mockvision.engine.v1.Host/StateWatch"
	Host_EventEmit_FullMethodName      = "/mockvision.engine.v1.Host/EventEmit"
	Host_EventSubscribe_FullMethodName = "/mockvision.engine.v1.Host/EventSubscribe"
	Host_DeliveryReport_FullMethodName = "/mockvision.engine.v1.Host/DeliveryReport"
	Host_EventTargets_FullMethodName   = "/mockvision.engine.v1.Host/EventTargets"
	Host_MediaStreams_FullMethodName   = "/mockvision.engine.v1.Host/MediaStreams"
	Host_MediaSnapshot_FullMethodName  = "/mockvision.engine.v1.Host/MediaSnapshot"
	Host_TemplateRender_FullMethodName = "/mockvision.engine.v1.Host/TemplateRender"
	Host_FileStatus_FullMethodName     = "/mockvision.engine.v1.Host/FileStatus"
	Host_FileFind_FullMethodName       = "/mockvision.engine.v1.Host/FileFind"
	Host_FileGet_FullMethodName        = "/mockvision.engine.v1.Host/FileGet"
	Host_FaultStatus_FullMethodName    = "/mockvision.engine.v1.Host/FaultStatus"
	Host_Log_FullMethodName            = "/mockvision.engine.v1.Host/Log"
	Host_RequestStat_FullMethodName    = "/mockvision.engine.v1.Host/RequestStat"
	Host_Gap_FullMethodName            = "/mockvision.engine.v1.Host/Gap"
	Host_Client_FullMethodName         = "/mockvision.engine.v1.Host/Client"
)

// HostClient is the client API for Host service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostClient interface {
	// Accounts: the camera's users, which can change while it runs.
	AccountsList(ctx context.Context, in *AccountsListRequest, opts ...grpc.CallOption) (*AccountsListResponse, error)
	// State
	StateGet(ctx context.Context, in *StateGetRequest, opts ...grpc.CallOption) (*StateGetResponse, error)
	StateList(ctx context.Context, in *StateListRequest, opts ...grpc.CallOption) (*StateListResponse, error)
	StateSet(ctx context.Context, in *StateSetRequest, opts ...grpc.CallOption) (*StateSetResponse, error)
	StateCanon(ctx context.Context, in *StateGetRequest, opts ...grpc.CallOption) (*StateGetResponse, error)
	StateWatch(ctx context.Context, in *StateWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateChanges], error)
	// Events
	EventEmit(ctx context.Context, in *EventEmitRequest, opts ...grpc.CallOption) (*EventEmitResponse, error)
	EventSubscribe(ctx context.Context, in *EventSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Dispatch], error)
	DeliveryReport(ctx context.Context, in *DeliveryReportRequest, opts ...grpc.CallOption) (*DeliveryReportResponse, error)
	// The targets the camera delivers a transport to now, for engines that
	// keep connections open to them (an MQTT client and its broker).
	EventTargets(ctx context.Context, in *EventSubscribeRequest, opts ...grpc.CallOption) (*EventTargetsResponse, error)
	// Media
	MediaStreams(ctx context.Context, in *MediaStreamsRequest, opts ...grpc.CallOption) (*MediaStreamsResponse, error)
	MediaSnapshot(ctx context.Context, in *MediaSnapshotRequest, opts ...grpc.CallOption) (*MediaSnapshotResponse, error)
	// Templates
	TemplateRender(ctx context.Context, in *TemplateRenderRequest, opts ...grpc.CallOption) (*TemplateRenderResponse, error)
	// Files: the recordings on the camera's SD card or NAS share, which the
	// host records; engines search and read them.
	FileStatus(ctx context.Context, in *FileStatusRequest, opts ...grpc.CallOption) (*StorageStatus, error)
	FileFind(ctx context.Context, in *FileFindRequest, opts ...grpc.CallOption) (*FileFindResponse, error)
	FileGet(ctx context.Context, in *FileGetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	// Faults: the status every request to an engine instance gets while an
	// injected fault is on; 0 when none.
	FaultStatus(ctx context.Context, in *FaultStatusRequest, opts ...grpc.CallOption) (*FaultStatusResponse, error)
	// Telemetry
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	RequestStat(ctx context.Context, in *RequestStatRequest, opts ...grpc.CallOption) (*RequestStatResponse, error)
	Gap(ctx context.Context, in *GapRequest, opts ...grpc.CallOption) (*GapResponse, error)
	Client(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error)
}

type hostClient struct {
	cc grpc.ClientConnInterface
}

func NewHostClient(cc grpc.ClientConnInterface) HostClient {
	return &hostClient{cc}
}

func (c *hostClient) AccountsList(ctx context.Context, in *AccountsListRequest, opts ...grpc.CallOption) (*AccountsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountsListResponse)
	err := c.cc.Invoke(ctx, Host_AccountsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) StateGet(ctx context.Context, in *StateGetRequest, opts ...grpc.CallOption) (*StateGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateGetResponse)
	err := c.cc.Invoke(ctx, Host_StateGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) StateList(ctx context.Context, in *StateListRequest, opts ...grpc.CallOption) (*StateListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateListResponse)
	err := c.cc.Invoke(ctx, Host_StateList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) StateSet(ctx context.Context, in *StateSetRequest, opts ...grpc.CallOption) (*StateSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateSetResponse)
	err := c.cc.Invoke(ctx, Host_StateSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) StateCanon(ctx context.Context, in *StateGetRequest, opts ...grpc.CallOption) (*StateGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateGetResponse)
	err := c.cc.Invoke(ctx, Host_StateCanon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) StateWatch(ctx context.Context, in *StateWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateChanges], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Host_ServiceDesc.Streams[0], Host_StateWatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StateWatchRequest, StateChanges]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Host_StateWatchClient = grpc.ServerStreamingClient[StateChanges]

func (c *hostClient) EventEmit(ctx context.Context, in *EventEmitRequest, opts ...grpc.CallOption) (*EventEmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventEmitResponse)
	err := c.cc.Invoke(ctx, Host_EventEmit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) EventSubscribe(ctx context.Context, in *EventSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Dispatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Host_ServiceDesc.Streams[1], Host_EventSubscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventSubscribeRequest, Dispatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Host_EventSubscribeClient = grpc.ServerStreamingClient[Dispatch]

func (c *hostClient) DeliveryReport(ctx context.Context, in *DeliveryReportRequest, opts ...grpc.CallOption) (*DeliveryReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryReportResponse)
	err := c.cc.Invoke(ctx, Host_DeliveryReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) EventTargets(ctx context.Context, in *EventSubscribeRequest, opts ...grpc.CallOption) (*EventTargetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventTargetsResponse)
	err := c.cc.Invoke(ctx, Host_EventTargets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) MediaStreams(ctx context.Context, in *MediaStreamsRequest, opts ...grpc.CallOption) (*MediaStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MediaStreamsResponse)
	err := c.cc.Invoke(ctx, Host_MediaStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) MediaSnapshot(ctx context.Context, in *MediaSnapshotRequest, opts ...grpc.CallOption) (*MediaSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MediaSnapshotResponse)
	err := c.cc.Invoke(ctx, Host_MediaSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) TemplateRender(ctx context.Context, in *TemplateRenderRequest, opts ...grpc.CallOption) (*TemplateRenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateRenderResponse)
	err := c.cc.Invoke(ctx, Host_TemplateRender_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) FileStatus(ctx context.Context, in *FileStatusRequest, opts ...grpc.CallOption) (*StorageStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageStatus)
	err := c.cc.Invoke(ctx, Host_FileStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) FileFind(ctx context.Context, in *FileFindRequest, opts ...grpc.CallOption) (*FileFindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileFindResponse)
	err := c.cc.Invoke(ctx, Host_FileFind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) FileGet(ctx context.Context, in *FileGetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Host_ServiceDesc.Streams[2], Host_FileGet_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileGetRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Host_FileGetClient = grpc.ServerStreamingClient[FileChunk]

func (c *hostClient) FaultStatus(ctx context.Context, in *FaultStatusRequest, opts ...grpc.CallOption) (*FaultStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FaultStatusResponse)
	err := c.cc.Invoke(ctx, Host_FaultStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, Host_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) RequestStat(ctx context.Context, in *RequestStatRequest, opts ...grpc.CallOption) (*RequestStatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestStatResponse)
	err := c.cc.Invoke(ctx, Host_RequestStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) Gap(ctx context.Context, in *GapRequest, opts ...grpc.CallOption) (*GapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GapResponse)
	err := c.cc.Invoke(ctx, Host_Gap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) Client(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, Host_Client_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServer is the server API for Host service.
// All implementations must embed UnimplementedHostServer
// for forward compatibility.
type HostServer interface {
	// Accounts: the camera's users, which can change while it runs.
	AccountsList(context.Context, *AccountsListRequest) (*AccountsListResponse, error)
	// State
	StateGet(context.Context, *StateGetRequest) (*StateGetResponse, error)
	StateList(context.Context, *StateListRequest) (*StateListResponse, error)
	StateSet(context.Context, *StateSetRequest) (*StateSetResponse, error)
	StateCanon(context.Context, *StateGetRequest) (*StateGetResponse, error)
	StateWatch(*StateWatchRequest, grpc.ServerStreamingServer[StateChanges]) error
	// Events
	EventEmit(context.Context, *EventEmitRequest) (*EventEmitResponse, error)
	EventSubscribe(*EventSubscribeRequest, grpc.ServerStreamingServer[Dispatch]) error
	DeliveryReport(context.Context, *DeliveryReportRequest) (*DeliveryReportResponse, error)
	// The targets the camera delivers a transport to now, for engines that
	// keep connections open to them (an MQTT client and its broker).
	EventTargets(context.Context, *EventSubscribeRequest) (*EventTargetsResponse, error)
	// Media
	MediaStreams(context.Context, *MediaStreamsRequest) (*MediaStreamsResponse, error)
	MediaSnapshot(context.Context, *MediaSnapshotRequest) (*MediaSnapshotResponse, error)
	// Templates
	TemplateRender(context.Context, *TemplateRenderRequest) (*TemplateRenderResponse, error)
	// Files: the recordings on the camera's SD card or NAS share, which the
	// host records; engines search and read them.
	FileStatus(context.Context, *FileStatusRequest) (*StorageStatus, error)
	FileFind(context.Context, *FileFindRequest) (*FileFindResponse, error)
	FileGet(*FileGetRequest, grpc.ServerStreamingServer[FileChunk]) error
	// Faults: the status every request to an engine instance gets while an
	// injected fault is on; 0 when none.
	FaultStatus(context.Context, *FaultStatusRequest) (*FaultStatusResponse, error)
	// Telemetry
	Log(context.Context, *LogRequest) (*LogResponse, error)
	RequestStat(context.Context, *RequestStatRequest) (*RequestStatResponse, error)
	Gap(context.Context, *GapRequest) (*GapResponse, error)
	Client(context.Context, *ClientRequest) (*ClientResponse, error)
	mustEmbedUnimplementedHostServer()
}

// UnimplementedHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServer struct{}

func (UnimplementedHostServer) AccountsList(context.Context, *AccountsListRequest) (*AccountsListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AccountsList not implemented")
}
func (UnimplementedHostServer) StateGet(context.Context, *StateGetRequest) (*StateGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StateGet not implemented")
}
func (UnimplementedHostServer) StateList(context.Context, *StateListRequest) (*StateListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StateList not implemented")
}
func (UnimplementedHostServer) StateSet(context.Context, *StateSetRequest) (*StateSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StateSet not implemented")
}
func (UnimplementedHostServer) StateCanon(context.Context, *StateGetRequest) (*StateGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StateCanon not implemented")
}
func (UnimplementedHostServer) StateWatch(*StateWatchRequest, grpc.ServerStreamingServer[StateChanges]) error {
	return status.Error(codes.Unimplemented, "method StateWatch not implemented")
}
func (UnimplementedHostServer) EventEmit(context.Context, *EventEmitRequest) (*EventEmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EventEmit not implemented")
}
func (UnimplementedHostServer) EventSubscribe(*EventSubscribeRequest, grpc.ServerStreamingServer[Dispatch]) error {
	return status.Error(codes.Unimplemented, "method EventSubscribe not implemented")
}
func (UnimplementedHostServer) DeliveryReport(context.Context, *DeliveryReportRequest) (*DeliveryReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliveryReport not implemented")
}
func (UnimplementedHostServer) EventTargets(context.Context, *EventSubscribeRequest) (*EventTargetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EventTargets not implemented")
}
func (UnimplementedHostServer) MediaStreams(context.Context, *MediaStreamsRequest) (*MediaStreamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MediaStreams not implemented")
}
func (UnimplementedHostServer) MediaSnapshot(context.Context, *MediaSnapshotRequest) (*MediaSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MediaSnapshot not implemented")
}
func (UnimplementedHostServer) TemplateRender(context.Context, *TemplateRenderRequest) (*TemplateRenderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TemplateRender not implemented")
}
func (UnimplementedHostServer) FileStatus(context.Context, *FileStatusRequest) (*StorageStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method FileStatus not implemented")
}
func (UnimplementedHostServer) FileFind(context.Context, *FileFindRequest) (*FileFindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileFind not implemented")
}
func (UnimplementedHostServer) FileGet(*FileGetRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method FileGet not implemented")
}
func (UnimplementedHostServer) FaultStatus(context.Context, *FaultStatusRequest) (*FaultStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FaultStatus not implemented")
}
func (UnimplementedHostServer) Log(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedHostServer) RequestStat(context.Context, *RequestStatRequest) (*RequestStatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestStat not implemented")
}
func (UnimplementedHostServer) Gap(context.Context, *GapRequest) (*GapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Gap not implemented")
}
func (UnimplementedHostServer) Client(context.Context, *ClientRequest) (*ClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Client not implemented")
}
func (UnimplementedHostServer) mustEmbedUnimplementedHostServer() {}
func (UnimplementedHostServer) testEmbeddedByValue()              {}

// UnsafeHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServer will
// result in compilation errors.
type UnsafeHostServer interface {
	mustEmbedUnimplementedHostServer()
}

func RegisterHostServer(s grpc.ServiceRegistrar, srv HostServer) {
	// If the following call panics, it indicates UnimplementedHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Host_ServiceDesc, srv)
}

func _Host_AccountsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).AccountsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_AccountsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).AccountsList(ctx, req.(*AccountsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_StateGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).StateGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_StateGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).StateGet(ctx, req.(*StateGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_StateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).StateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_StateList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).StateList(ctx, req.(*StateListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_StateSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).StateSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_StateSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).StateSet(ctx, req.(*StateSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_StateCanon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).StateCanon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_StateCanon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).StateCanon(ctx, req.(*StateGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_StateWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StateWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostServer).StateWatch(m, &grpc.GenericServerStream[StateWatchRequest, StateChanges]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Host_StateWatchServer = grpc.ServerStreamingServer[StateChanges]

func _Host_EventEmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventEmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).EventEmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_EventEmit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).EventEmit(ctx, req.(*EventEmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_EventSubscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostServer).EventSubscribe(m, &grpc.GenericServerStream[EventSubscribeRequest, Dispatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Host_EventSubscribeServer = grpc.ServerStreamingServer[Dispatch]

func _Host_DeliveryReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).DeliveryReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_DeliveryReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).DeliveryReport(ctx, req.(*DeliveryReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_EventTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventSubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).EventTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_EventTargets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).EventTargets(ctx, req.(*EventSubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_MediaStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediaStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).MediaStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_MediaStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).MediaStreams(ctx, req.(*MediaStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_MediaSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediaSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).MediaSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_MediaSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).MediaSnapshot(ctx, req.(*MediaSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_TemplateRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateRenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).TemplateRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_TemplateRender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).TemplateRender(ctx, req.(*TemplateRenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_FileStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).FileStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_FileStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).FileStatus(ctx, req.(*FileStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_FileFind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).FileFind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_FileFind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).FileFind(ctx, req.(*FileFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_FileGet_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileGetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostServer).FileGet(m, &grpc.GenericServerStream[FileGetRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Host_FileGetServer = grpc.ServerStreamingServer[FileChunk]

func _Host_FaultStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FaultStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).FaultStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_FaultStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).FaultStatus(ctx, req.(*FaultStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_RequestStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).RequestStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_RequestStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).RequestStat(ctx, req.(*RequestStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_Gap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).Gap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_Gap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).Gap(ctx, req.(*GapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_Client_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).Client(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_Client_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).Client(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Host_ServiceDesc is the grpc.ServiceDesc for Host service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Host_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mockvision.engine.v1.Host",
	HandlerType: (*HostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountsList",
			Handler:    _Host_AccountsList_Handler,
		},
		{
			MethodName: "StateGet",
			Handler:    _Host_StateGet_Handler,
		},
		{
			MethodName: "StateList",
			Handler:    _Host_StateList_Handler,
		},
		{
			MethodName: "StateSet",
			Handler:    _Host_StateSet_Handler,
		},
		{
			MethodName: "StateCanon",
			Handler:    _Host_StateCanon_Handler,
		},
		{
			MethodName: "EventEmit",
			Handler:    _Host_EventEmit_Handler,
		},
		{
			MethodName: "DeliveryReport",
			Handler:    _Host_DeliveryReport_Handler,
		},
		{
			MethodName: "EventTargets",
			Handler:    _Host_EventTargets_Handler,
		},
		{
			MethodName: "MediaStreams",
			Handler:    _Host_MediaStreams_Handler,
		},
		{
			MethodName: "MediaSnapshot",
			Handler:    _Host_MediaSnapshot_Handler,
		},
		{
			MethodName: "TemplateRender",
			Handler:    _Host_TemplateRender_Handler,
		},
		{
			MethodName: "FileStatus",
			Handler:    _Host_FileStatus_Handler,
		},
		{
			MethodName: "FileFind",
			Handler:    _Host_FileFind_Handler,
		},
		{
			MethodName: "FaultStatus",
			Handler:    _Host_FaultStatus_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _Host_Log_Handler,
		},
		{
			MethodName: "RequestStat",
			Handler:    _Host_RequestStat_Handler,
		},
		{
			MethodName: "Gap",
			Handler:    _Host_Gap_Handler,
		},
		{
			MethodName: "Client",
			Handler:    _Host_Client_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StateWatch",
			Handler:       _Host_StateWatch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EventSubscribe",
			Handler:       _Host_EventSubscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FileGet",
			Handler:       _Host_FileGet_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sdk/proto/mockvision/engine/v1/engine.proto",
}
