// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const deleteAuditBefore = `-- name: DeleteAuditBefore :execrows
DELETE FROM audit_log WHERE at < ?1
`

func (q *Queries) DeleteAuditBefore(ctx context.Context, before int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuditBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAudit = `-- name: GetAudit :one
SELECT audit_log.id, audit_log.at, audit_log.actor_type, audit_log.actor_id, audit_log."action", audit_log.entity_type, audit_log.entity_id, audit_log.origin_ip, audit_log.diff_json, audit_log.origin, audit_log.actor_name, audit_log.token_id, audit_log.token_name,
       CAST(coalesce(cameras.name, targets.name, assets.filename, users.username, api_tokens.name,
                     profiles.profile_id || '@' || profiles.version, '') AS TEXT) AS entity_name
FROM audit_log
LEFT JOIN cameras ON audit_log.entity_type = 'camera' AND cameras.id = audit_log.entity_id
LEFT JOIN targets ON audit_log.entity_type = 'target' AND targets.id = audit_log.entity_id
LEFT JOIN assets ON audit_log.entity_type = 'asset' AND assets.id = audit_log.entity_id
LEFT JOIN users ON audit_log.entity_type = 'user' AND users.id = audit_log.entity_id
LEFT JOIN api_tokens ON audit_log.entity_type = 'token' AND api_tokens.id = audit_log.entity_id
LEFT JOIN profiles ON audit_log.entity_type = 'profile' AND profiles.id = audit_log.entity_id
WHERE audit_log.id = ?1
`

type GetAuditRow struct {
	ID         string
	At         int64
	ActorType  string
	ActorID    string
	Action     string
	EntityType string
	EntityID   string
	OriginIp   string
	DiffJson   string
	Origin     string
	ActorName  string
	TokenID    string
	TokenName  string
	EntityName string
}

func (q *Queries) GetAudit(ctx context.Context, id string) (GetAuditRow, error) {
	row := q.db.QueryRowContext(ctx, getAudit, id)
	var i GetAuditRow
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.OriginIp,
		&i.DiffJson,
		&i.Origin,
		&i.ActorName,
		&i.TokenID,
		&i.TokenName,
		&i.EntityName,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (id, at, actor_type, actor_id, actor_name, origin, origin_ip, token_id, token_name, action, entity_type, entity_id, diff_json)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13)
`

type InsertAuditParams struct {
	ID         string
	At         int64
	ActorType  string
	ActorID    string
	ActorName  string
	Origin     string
	OriginIp   string
	TokenID    string
	TokenName  string
	Action     string
	EntityType string
	EntityID   string
	DiffJson   string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.ID,
		arg.At,
		arg.ActorType,
		arg.ActorID,
		arg.ActorName,
		arg.Origin,
		arg.OriginIp,
		arg.TokenID,
		arg.TokenName,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.DiffJson,
	)
	return err
}

const listAudit = `-- name: ListAudit :many

SELECT audit_log.id, audit_log.at, audit_log.actor_type, audit_log.actor_id, audit_log."action", audit_log.entity_type, audit_log.entity_id, audit_log.origin_ip, audit_log.diff_json, audit_log.origin, audit_log.actor_name, audit_log.token_id, audit_log.token_name,
       CAST(coalesce(cameras.name, targets.name, assets.filename, users.username, api_tokens.name,
                     profiles.profile_id || '@' || profiles.version, '') AS TEXT) AS entity_name
FROM audit_log
LEFT JOIN cameras ON audit_log.entity_type = 'camera' AND cameras.id = audit_log.entity_id
LEFT JOIN targets ON audit_log.entity_type = 'target' AND targets.id = audit_log.entity_id
LEFT JOIN assets ON audit_log.entity_type = 'asset' AND assets.id = audit_log.entity_id
LEFT JOIN users ON audit_log.entity_type = 'user' AND users.id = audit_log.entity_id
LEFT JOIN api_tokens ON audit_log.entity_type = 'token' AND api_tokens.id = audit_log.entity_id
LEFT JOIN profiles ON audit_log.entity_type = 'profile' AND profiles.id = audit_log.entity_id
WHERE (CAST(?1 AS TEXT) = '' OR audit_log.id < CAST(?1 AS TEXT))
  AND (CAST(?2 AS TEXT) = '' OR audit_log.origin = CAST(?2 AS TEXT))
  AND (CAST(?3 AS TEXT) = '' OR audit_log.entity_type = CAST(?3 AS TEXT))
  AND (CAST(?4 AS TEXT) = '' OR audit_log.entity_id = CAST(?4 AS TEXT))
  AND (CAST(?5 AS TEXT) = '' OR audit_log.token_id = CAST(?5 AS TEXT))
  AND (CAST(?6 AS TEXT) = '' OR audit_log.action = CAST(?6 AS TEXT) OR audit_log.action LIKE CAST(?6 AS TEXT) || '.%')
  AND (CAST(?7 AS INTEGER) = 0 OR audit_log.at >= CAST(?7 AS INTEGER))
  AND (CAST(?8 AS INTEGER) = 0 OR audit_log.at < CAST(?8 AS INTEGER))
ORDER BY audit_log.id DESC
LIMIT ?9
`

type ListAuditParams struct {
	Cursor     string
	Origin     string
	EntityType string
	EntityID   string
	TokenID    string
	Action     string
	Since      int64
	Until      int64
	Limit      int64
}

type ListAuditRow struct {
	ID         string
	At         int64
	ActorType  string
	ActorID    string
	Action     string
	EntityType string
	EntityID   string
	OriginIp   string
	DiffJson   string
	Origin     string
	ActorName  string
	TokenID    string
	TokenName  string
	EntityName string
}

// The entity name is resolved while it still exists; entries of deleted
// entities keep the name in their diff.
func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]ListAuditRow, error) {
	rows, err := q.db.QueryContext(ctx, listAudit,
		arg.Cursor,
		arg.Origin,
		arg.EntityType,
		arg.EntityID,
		arg.TokenID,
		arg.Action,
		arg.Since,
		arg.Until,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditRow{}
	for rows.Next() {
		var i ListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OriginIp,
			&i.DiffJson,
			&i.Origin,
			&i.ActorName,
			&i.TokenID,
			&i.TokenName,
			&i.EntityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
