// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, expires_at, ip, user_agent, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	ExpiresAt int64
	Ip        string
	UserAgent string
	CreatedAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, password_hash, role, disabled, created_at)
VALUES (?1, ?2, ?3, ?4, 0, ?5)
`

type CreateUserParams struct {
	ID           string
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const deleteAuditBefore = `-- name: DeleteAuditBefore :execrows
DELETE FROM audit_log WHERE at < ?1
`

func (q *Queries) DeleteAuditBefore(ctx context.Context, before int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuditBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < ?1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE sessions SET expires_at = ?1 WHERE id = ?2
`

type ExtendSessionParams struct {
	ExpiresAt int64
	ID        string
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.ExecContext(ctx, extendSession, arg.ExpiresAt, arg.ID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT sessions.id, sessions.user_id, sessions.expires_at, users.username, users.role, users.disabled
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.id = ?1
`

type GetSessionRow struct {
	ID        string
	UserID    string
	ExpiresAt int64
	Username  string
	Role      string
	Disabled  int64
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Username,
		&i.Role,
		&i.Disabled,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value_json FROM settings WHERE key = ?1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value_json string
	err := row.Scan(&value_json)
	return value_json, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, disabled, created_at FROM users WHERE id = ?1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, disabled, created_at FROM users WHERE username = ?1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (id, at, actor_type, actor_id, action, entity_type, entity_id, origin_ip, diff_json)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type InsertAuditParams struct {
	ID         string
	At         int64
	ActorType  string
	ActorID    string
	Action     string
	EntityType string
	EntityID   string
	OriginIp   string
	DiffJson   string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.ID,
		arg.At,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OriginIp,
		arg.DiffJson,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, at, actor_type, actor_id, "action", entity_type, entity_id, origin_ip, diff_json FROM audit_log
WHERE (CAST(?1 AS TEXT) = '' OR id < CAST(?1 AS TEXT))
ORDER BY id DESC
LIMIT ?2
`

type ListAuditParams struct {
	Cursor string
	Limit  int64
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OriginIp,
			&i.DiffJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT "key", value_json FROM settings ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.ValueJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value_json) VALUES (?1, ?2)
ON CONFLICT (key) DO UPDATE SET value_json = excluded.value_json
`

type UpsertSettingParams struct {
	Key       string
	ValueJson string
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.ValueJson)
	return err
}
