// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cameras.sql

package db

import (
	"context"
	"database/sql"
)

const cameraIDByIP = `-- name: CameraIDByIP :one
SELECT camera_id FROM camera_network WHERE ip = ?1
`

func (q *Queries) CameraIDByIP(ctx context.Context, ip string) (string, error) {
	row := q.db.QueryRowContext(ctx, cameraIDByIP, ip)
	var camera_id string
	err := row.Scan(&camera_id)
	return camera_id, err
}

const cameraIDByMAC = `-- name: CameraIDByMAC :one
SELECT camera_id FROM camera_network WHERE mac = ?1
`

func (q *Queries) CameraIDByMAC(ctx context.Context, mac string) (string, error) {
	row := q.db.QueryRowContext(ctx, cameraIDByMAC, mac)
	var camera_id string
	err := row.Scan(&camera_id)
	return camera_id, err
}

const cameraIDByName = `-- name: CameraIDByName :one
SELECT id FROM cameras WHERE name = ?1
`

func (q *Queries) CameraIDByName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, cameraIDByName, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const camerasUsingTarget = `-- name: CamerasUsingTarget :many
SELECT camera_id FROM camera_targets WHERE target_id = ?1
`

func (q *Queries) CamerasUsingTarget(ctx context.Context, targetID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, camerasUsingTarget, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var camera_id string
		if err := rows.Scan(&camera_id); err != nil {
			return nil, err
		}
		items = append(items, camera_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCameras = `-- name: CountCameras :one
SELECT count(*) FROM cameras
`

func (q *Queries) CountCameras(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCameras)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCamera = `-- name: DeleteCamera :execrows
DELETE FROM cameras WHERE id = ?1
`

func (q *Queries) DeleteCamera(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCamera, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCameraTargets = `-- name: DeleteCameraTargets :exec
DELETE FROM camera_targets WHERE camera_id = ?1
`

func (q *Queries) DeleteCameraTargets(ctx context.Context, cameraID string) error {
	_, err := q.db.ExecContext(ctx, deleteCameraTargets, cameraID)
	return err
}

const getCamera = `-- name: GetCamera :one
SELECT id, name, profile_id, profile_version, serial, desired_state, autostart, tags_json, created_at, updated_at FROM cameras WHERE id = ?1
`

func (q *Queries) GetCamera(ctx context.Context, id string) (Camera, error) {
	row := q.db.QueryRowContext(ctx, getCamera, id)
	var i Camera
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProfileID,
		&i.ProfileVersion,
		&i.Serial,
		&i.DesiredState,
		&i.Autostart,
		&i.TagsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCameraNetwork = `-- name: GetCameraNetwork :one
SELECT camera_id, mode, parent_if, mac, ip_mode, ip, netmask, gateway, dns_json FROM camera_network WHERE camera_id = ?1
`

func (q *Queries) GetCameraNetwork(ctx context.Context, cameraID string) (CameraNetwork, error) {
	row := q.db.QueryRowContext(ctx, getCameraNetwork, cameraID)
	var i CameraNetwork
	err := row.Scan(
		&i.CameraID,
		&i.Mode,
		&i.ParentIf,
		&i.Mac,
		&i.IpMode,
		&i.Ip,
		&i.Netmask,
		&i.Gateway,
		&i.DnsJson,
	)
	return i, err
}

const getCameraStatus = `-- name: GetCameraStatus :one
SELECT camera_id, actual_state, reason, started_at, last_heartbeat, updated_at FROM camera_status WHERE camera_id = ?1
`

func (q *Queries) GetCameraStatus(ctx context.Context, cameraID string) (CameraStatus, error) {
	row := q.db.QueryRowContext(ctx, getCameraStatus, cameraID)
	var i CameraStatus
	err := row.Scan(
		&i.CameraID,
		&i.ActualState,
		&i.Reason,
		&i.StartedAt,
		&i.LastHeartbeat,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCamera = `-- name: InsertCamera :exec
INSERT INTO cameras (id, name, profile_id, profile_version, serial, desired_state, autostart, tags_json, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
`

type InsertCameraParams struct {
	ID             string
	Name           string
	ProfileID      string
	ProfileVersion string
	Serial         string
	DesiredState   string
	Autostart      int64
	TagsJson       string
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) InsertCamera(ctx context.Context, arg InsertCameraParams) error {
	_, err := q.db.ExecContext(ctx, insertCamera,
		arg.ID,
		arg.Name,
		arg.ProfileID,
		arg.ProfileVersion,
		arg.Serial,
		arg.DesiredState,
		arg.Autostart,
		arg.TagsJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertCameraNetwork = `-- name: InsertCameraNetwork :exec
INSERT INTO camera_network (camera_id, mode, parent_if, mac, ip_mode, ip, netmask, gateway, dns_json)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type InsertCameraNetworkParams struct {
	CameraID string
	Mode     string
	ParentIf string
	Mac      string
	IpMode   string
	Ip       string
	Netmask  string
	Gateway  string
	DnsJson  string
}

func (q *Queries) InsertCameraNetwork(ctx context.Context, arg InsertCameraNetworkParams) error {
	_, err := q.db.ExecContext(ctx, insertCameraNetwork,
		arg.CameraID,
		arg.Mode,
		arg.ParentIf,
		arg.Mac,
		arg.IpMode,
		arg.Ip,
		arg.Netmask,
		arg.Gateway,
		arg.DnsJson,
	)
	return err
}

const insertCameraProtocol = `-- name: InsertCameraProtocol :exec
INSERT INTO camera_protocols (camera_id, engine_key, enabled, port, options_json)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertCameraProtocolParams struct {
	CameraID    string
	EngineKey   string
	Enabled     int64
	Port        int64
	OptionsJson string
}

func (q *Queries) InsertCameraProtocol(ctx context.Context, arg InsertCameraProtocolParams) error {
	_, err := q.db.ExecContext(ctx, insertCameraProtocol,
		arg.CameraID,
		arg.EngineKey,
		arg.Enabled,
		arg.Port,
		arg.OptionsJson,
	)
	return err
}

const insertCameraTarget = `-- name: InsertCameraTarget :exec
INSERT INTO camera_targets (camera_id, target_id, event_types_json, overrides_json)
VALUES (?1, ?2, ?3, ?4)
`

type InsertCameraTargetParams struct {
	CameraID       string
	TargetID       string
	EventTypesJson string
	OverridesJson  string
}

func (q *Queries) InsertCameraTarget(ctx context.Context, arg InsertCameraTargetParams) error {
	_, err := q.db.ExecContext(ctx, insertCameraTarget,
		arg.CameraID,
		arg.TargetID,
		arg.EventTypesJson,
		arg.OverridesJson,
	)
	return err
}

const insertCameraUser = `-- name: InsertCameraUser :exec
INSERT INTO camera_users (id, camera_id, username, password_enc, role)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertCameraUserParams struct {
	ID          string
	CameraID    string
	Username    string
	PasswordEnc []byte
	Role        string
}

func (q *Queries) InsertCameraUser(ctx context.Context, arg InsertCameraUserParams) error {
	_, err := q.db.ExecContext(ctx, insertCameraUser,
		arg.ID,
		arg.CameraID,
		arg.Username,
		arg.PasswordEnc,
		arg.Role,
	)
	return err
}

const listCameraNetworks = `-- name: ListCameraNetworks :many
SELECT camera_id, mode, parent_if, mac, ip_mode, ip, netmask, gateway, dns_json FROM camera_network
`

func (q *Queries) ListCameraNetworks(ctx context.Context) ([]CameraNetwork, error) {
	rows, err := q.db.QueryContext(ctx, listCameraNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraNetwork{}
	for rows.Next() {
		var i CameraNetwork
		if err := rows.Scan(
			&i.CameraID,
			&i.Mode,
			&i.ParentIf,
			&i.Mac,
			&i.IpMode,
			&i.Ip,
			&i.Netmask,
			&i.Gateway,
			&i.DnsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraProtocols = `-- name: ListCameraProtocols :many
SELECT camera_id, engine_key, enabled, port, options_json FROM camera_protocols WHERE camera_id = ?1 ORDER BY engine_key
`

func (q *Queries) ListCameraProtocols(ctx context.Context, cameraID string) ([]CameraProtocol, error) {
	rows, err := q.db.QueryContext(ctx, listCameraProtocols, cameraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraProtocol{}
	for rows.Next() {
		var i CameraProtocol
		if err := rows.Scan(
			&i.CameraID,
			&i.EngineKey,
			&i.Enabled,
			&i.Port,
			&i.OptionsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraState = `-- name: ListCameraState :many
SELECT camera_id, "key", value_json, origin, updated_at FROM camera_state WHERE camera_id = ?1 ORDER BY key
`

func (q *Queries) ListCameraState(ctx context.Context, cameraID string) ([]CameraState, error) {
	rows, err := q.db.QueryContext(ctx, listCameraState, cameraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraState{}
	for rows.Next() {
		var i CameraState
		if err := rows.Scan(
			&i.CameraID,
			&i.Key,
			&i.ValueJson,
			&i.Origin,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraStatuses = `-- name: ListCameraStatuses :many
SELECT camera_id, actual_state, reason, started_at, last_heartbeat, updated_at FROM camera_status
`

func (q *Queries) ListCameraStatuses(ctx context.Context) ([]CameraStatus, error) {
	rows, err := q.db.QueryContext(ctx, listCameraStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraStatus{}
	for rows.Next() {
		var i CameraStatus
		if err := rows.Scan(
			&i.CameraID,
			&i.ActualState,
			&i.Reason,
			&i.StartedAt,
			&i.LastHeartbeat,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraStreams = `-- name: ListCameraStreams :many
SELECT camera_id, stream, asset_id, rendition_id FROM camera_streams WHERE camera_id = ?1 ORDER BY stream
`

func (q *Queries) ListCameraStreams(ctx context.Context, cameraID string) ([]CameraStream, error) {
	rows, err := q.db.QueryContext(ctx, listCameraStreams, cameraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraStream{}
	for rows.Next() {
		var i CameraStream
		if err := rows.Scan(
			&i.CameraID,
			&i.Stream,
			&i.AssetID,
			&i.RenditionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraTargets = `-- name: ListCameraTargets :many
SELECT camera_targets.camera_id, camera_targets.event_types_json, camera_targets.overrides_json,
       targets.id, targets.name, targets.type, targets.config_json, targets.secret_enc, targets.enabled
FROM camera_targets
JOIN targets ON targets.id = camera_targets.target_id
WHERE camera_targets.camera_id = ?1
ORDER BY targets.name
`

type ListCameraTargetsRow struct {
	CameraID       string
	EventTypesJson string
	OverridesJson  string
	ID             string
	Name           string
	Type           string
	ConfigJson     string
	SecretEnc      []byte
	Enabled        int64
}

func (q *Queries) ListCameraTargets(ctx context.Context, cameraID string) ([]ListCameraTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCameraTargets, cameraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCameraTargetsRow{}
	for rows.Next() {
		var i ListCameraTargetsRow
		if err := rows.Scan(
			&i.CameraID,
			&i.EventTypesJson,
			&i.OverridesJson,
			&i.ID,
			&i.Name,
			&i.Type,
			&i.ConfigJson,
			&i.SecretEnc,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraUsers = `-- name: ListCameraUsers :many
SELECT id, camera_id, username, password_enc, role FROM camera_users WHERE camera_id = ?1 ORDER BY username
`

func (q *Queries) ListCameraUsers(ctx context.Context, cameraID string) ([]CameraUser, error) {
	rows, err := q.db.QueryContext(ctx, listCameraUsers, cameraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraUser{}
	for rows.Next() {
		var i CameraUser
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Username,
			&i.PasswordEnc,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameras = `-- name: ListCameras :many
SELECT id, name, profile_id, profile_version, serial, desired_state, autostart, tags_json, created_at, updated_at FROM cameras ORDER BY name
`

func (q *Queries) ListCameras(ctx context.Context) ([]Camera, error) {
	rows, err := q.db.QueryContext(ctx, listCameras)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Camera{}
	for rows.Next() {
		var i Camera
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProfileID,
			&i.ProfileVersion,
			&i.Serial,
			&i.DesiredState,
			&i.Autostart,
			&i.TagsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCameraDesired = `-- name: SetCameraDesired :exec
UPDATE cameras SET desired_state = ?1, updated_at = ?2 WHERE id = ?3
`

type SetCameraDesiredParams struct {
	DesiredState string
	UpdatedAt    int64
	ID           string
}

func (q *Queries) SetCameraDesired(ctx context.Context, arg SetCameraDesiredParams) error {
	_, err := q.db.ExecContext(ctx, setCameraDesired, arg.DesiredState, arg.UpdatedAt, arg.ID)
	return err
}

const updateCameraMeta = `-- name: UpdateCameraMeta :exec
UPDATE cameras SET name = ?1, autostart = ?2, tags_json = ?3, updated_at = ?4 WHERE id = ?5
`

type UpdateCameraMetaParams struct {
	Name      string
	Autostart int64
	TagsJson  string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateCameraMeta(ctx context.Context, arg UpdateCameraMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateCameraMeta,
		arg.Name,
		arg.Autostart,
		arg.TagsJson,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertCameraState = `-- name: UpsertCameraState :exec
INSERT INTO camera_state (camera_id, key, value_json, origin, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (camera_id, key) DO UPDATE SET
  value_json = excluded.value_json, origin = excluded.origin, updated_at = excluded.updated_at
`

type UpsertCameraStateParams struct {
	CameraID  string
	Key       string
	ValueJson string
	Origin    string
	UpdatedAt int64
}

func (q *Queries) UpsertCameraState(ctx context.Context, arg UpsertCameraStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertCameraState,
		arg.CameraID,
		arg.Key,
		arg.ValueJson,
		arg.Origin,
		arg.UpdatedAt,
	)
	return err
}

const upsertCameraStatus = `-- name: UpsertCameraStatus :exec
INSERT INTO camera_status (camera_id, actual_state, reason, started_at, last_heartbeat, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (camera_id) DO UPDATE SET
  actual_state = excluded.actual_state, reason = excluded.reason, started_at = excluded.started_at,
  last_heartbeat = excluded.last_heartbeat, updated_at = excluded.updated_at
`

type UpsertCameraStatusParams struct {
	CameraID      string
	ActualState   string
	Reason        string
	StartedAt     sql.NullInt64
	LastHeartbeat sql.NullInt64
	UpdatedAt     int64
}

func (q *Queries) UpsertCameraStatus(ctx context.Context, arg UpsertCameraStatusParams) error {
	_, err := q.db.ExecContext(ctx, upsertCameraStatus,
		arg.CameraID,
		arg.ActualState,
		arg.Reason,
		arg.StartedAt,
		arg.LastHeartbeat,
		arg.UpdatedAt,
	)
	return err
}

const upsertCameraStream = `-- name: UpsertCameraStream :exec
INSERT INTO camera_streams (camera_id, stream, asset_id, rendition_id)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (camera_id, stream) DO UPDATE SET asset_id = excluded.asset_id, rendition_id = excluded.rendition_id
`

type UpsertCameraStreamParams struct {
	CameraID    string
	Stream      string
	AssetID     string
	RenditionID sql.NullString
}

func (q *Queries) UpsertCameraStream(ctx context.Context, arg UpsertCameraStreamParams) error {
	_, err := q.db.ExecContext(ctx, upsertCameraStream,
		arg.CameraID,
		arg.Stream,
		arg.AssetID,
		arg.RenditionID,
	)
	return err
}
