// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"
	"database/sql"
)

const countDevicesByHost = `-- name: CountDevicesByHost :one
SELECT count(*) FROM devices WHERE host = ?1 AND id <> ?2
`

type CountDevicesByHostParams struct {
	Host string
	ID   string
}

func (q *Queries) CountDevicesByHost(ctx context.Context, arg CountDevicesByHostParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDevicesByHost, arg.Host, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices WHERE id = ?1
`

func (q *Queries) DeleteDevice(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishCapture = `-- name: FinishCapture :exec
UPDATE captures SET status = ?1, artifacts_json = ?2, draft_profile_id = ?3, finished_at = ?4 WHERE id = ?5
`

type FinishCaptureParams struct {
	Status         string
	ArtifactsJson  string
	DraftProfileID sql.NullString
	FinishedAt     sql.NullInt64
	ID             string
}

func (q *Queries) FinishCapture(ctx context.Context, arg FinishCaptureParams) error {
	_, err := q.db.ExecContext(ctx, finishCapture,
		arg.Status,
		arg.ArtifactsJson,
		arg.DraftProfileID,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const getCapture = `-- name: GetCapture :one
SELECT id, device_id, job_id, program_ref, status, artifacts_json, draft_profile_id, created_at, finished_at FROM captures WHERE id = ?1
`

func (q *Queries) GetCapture(ctx context.Context, id string) (Capture, error) {
	row := q.db.QueryRowContext(ctx, getCapture, id)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.JobID,
		&i.ProgramRef,
		&i.Status,
		&i.ArtifactsJson,
		&i.DraftProfileID,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, name, host, ports_json, username, secret_enc, kind, authorized, detected_json, created_at, updated_at, port_map_json FROM devices WHERE id = ?1
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.PortsJson,
		&i.Username,
		&i.SecretEnc,
		&i.Kind,
		&i.Authorized,
		&i.DetectedJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortMapJson,
	)
	return i, err
}

const getProgramByRef = `-- name: GetProgramByRef :one
SELECT id, package_id, program_id, version, name, compatible_json, steps_json, installed_at FROM programs WHERE program_id = ?1 AND version = ?2
`

type GetProgramByRefParams struct {
	ProgramID string
	Version   string
}

func (q *Queries) GetProgramByRef(ctx context.Context, arg GetProgramByRefParams) (Program, error) {
	row := q.db.QueryRowContext(ctx, getProgramByRef, arg.ProgramID, arg.Version)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.ProgramID,
		&i.Version,
		&i.Name,
		&i.CompatibleJson,
		&i.StepsJson,
		&i.InstalledAt,
	)
	return i, err
}

const insertCapture = `-- name: InsertCapture :exec
INSERT INTO captures (id, device_id, job_id, program_ref, status, artifacts_json, draft_profile_id, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
`

type InsertCaptureParams struct {
	ID             string
	DeviceID       string
	JobID          string
	ProgramRef     string
	Status         string
	ArtifactsJson  string
	DraftProfileID sql.NullString
	CreatedAt      int64
}

func (q *Queries) InsertCapture(ctx context.Context, arg InsertCaptureParams) error {
	_, err := q.db.ExecContext(ctx, insertCapture,
		arg.ID,
		arg.DeviceID,
		arg.JobID,
		arg.ProgramRef,
		arg.Status,
		arg.ArtifactsJson,
		arg.DraftProfileID,
		arg.CreatedAt,
	)
	return err
}

const insertDevice = `-- name: InsertDevice :exec
INSERT INTO devices (id, name, host, ports_json, port_map_json, username, secret_enc, kind, authorized, detected_json, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
`

type InsertDeviceParams struct {
	ID           string
	Name         string
	Host         string
	PortsJson    string
	PortMapJson  string
	Username     string
	SecretEnc    []byte
	Kind         string
	Authorized   int64
	DetectedJson string
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, insertDevice,
		arg.ID,
		arg.Name,
		arg.Host,
		arg.PortsJson,
		arg.PortMapJson,
		arg.Username,
		arg.SecretEnc,
		arg.Kind,
		arg.Authorized,
		arg.DetectedJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertProgram = `-- name: InsertProgram :exec
INSERT INTO programs (id, package_id, program_id, version, name, compatible_json, steps_json, installed_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
`

type InsertProgramParams struct {
	ID             string
	PackageID      string
	ProgramID      string
	Version        string
	Name           string
	CompatibleJson string
	StepsJson      string
	InstalledAt    int64
}

func (q *Queries) InsertProgram(ctx context.Context, arg InsertProgramParams) error {
	_, err := q.db.ExecContext(ctx, insertProgram,
		arg.ID,
		arg.PackageID,
		arg.ProgramID,
		arg.Version,
		arg.Name,
		arg.CompatibleJson,
		arg.StepsJson,
		arg.InstalledAt,
	)
	return err
}

const listCaptures = `-- name: ListCaptures :many
SELECT id, device_id, job_id, program_ref, status, artifacts_json, draft_profile_id, created_at, finished_at FROM captures ORDER BY created_at DESC LIMIT ?1
`

func (q *Queries) ListCaptures(ctx context.Context, lim int64) ([]Capture, error) {
	rows, err := q.db.QueryContext(ctx, listCaptures, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Capture{}
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.JobID,
			&i.ProgramRef,
			&i.Status,
			&i.ArtifactsJson,
			&i.DraftProfileID,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapturesByDevice = `-- name: ListCapturesByDevice :many
SELECT id, device_id, job_id, program_ref, status, artifacts_json, draft_profile_id, created_at, finished_at FROM captures WHERE device_id = ?1 ORDER BY created_at DESC LIMIT ?2
`

type ListCapturesByDeviceParams struct {
	DeviceID string
	Lim      int64
}

func (q *Queries) ListCapturesByDevice(ctx context.Context, arg ListCapturesByDeviceParams) ([]Capture, error) {
	rows, err := q.db.QueryContext(ctx, listCapturesByDevice, arg.DeviceID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Capture{}
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.JobID,
			&i.ProgramRef,
			&i.Status,
			&i.ArtifactsJson,
			&i.DraftProfileID,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, host, ports_json, username, secret_enc, kind, authorized, detected_json, created_at, updated_at, port_map_json FROM devices ORDER BY created_at DESC
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.PortsJson,
			&i.Username,
			&i.SecretEnc,
			&i.Kind,
			&i.Authorized,
			&i.DetectedJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PortMapJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT programs.id, programs.package_id, programs.program_id, programs.version, programs.name, programs.compatible_json, programs.steps_json, programs.installed_at, packages.signature_status, packages.signer FROM programs
JOIN packages ON packages.id = programs.package_id
ORDER BY programs.program_id
`

type ListProgramsRow struct {
	ID              string
	PackageID       string
	ProgramID       string
	Version         string
	Name            string
	CompatibleJson  string
	StepsJson       string
	InstalledAt     int64
	SignatureStatus string
	Signer          string
}

func (q *Queries) ListPrograms(ctx context.Context) ([]ListProgramsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramsRow{}
	for rows.Next() {
		var i ListProgramsRow
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.ProgramID,
			&i.Version,
			&i.Name,
			&i.CompatibleJson,
			&i.StepsJson,
			&i.InstalledAt,
			&i.SignatureStatus,
			&i.Signer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCaptureJob = `-- name: SetCaptureJob :exec
UPDATE captures SET job_id = ?1 WHERE id = ?2
`

type SetCaptureJobParams struct {
	JobID string
	ID    string
}

func (q *Queries) SetCaptureJob(ctx context.Context, arg SetCaptureJobParams) error {
	_, err := q.db.ExecContext(ctx, setCaptureJob, arg.JobID, arg.ID)
	return err
}

const setDeviceDetected = `-- name: SetDeviceDetected :exec
UPDATE devices SET detected_json = ?1, kind = ?2, updated_at = ?3 WHERE id = ?4
`

type SetDeviceDetectedParams struct {
	DetectedJson string
	Kind         string
	UpdatedAt    int64
	ID           string
}

func (q *Queries) SetDeviceDetected(ctx context.Context, arg SetDeviceDetectedParams) error {
	_, err := q.db.ExecContext(ctx, setDeviceDetected,
		arg.DetectedJson,
		arg.Kind,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateDevice = `-- name: UpdateDevice :exec
UPDATE devices SET name = ?1, host = ?2, ports_json = ?3, port_map_json = ?4, username = ?5,
  secret_enc = ?6, kind = ?7, authorized = ?8, updated_at = ?9 WHERE id = ?10
`

type UpdateDeviceParams struct {
	Name        string
	Host        string
	PortsJson   string
	PortMapJson string
	Username    string
	SecretEnc   []byte
	Kind        string
	Authorized  int64
	UpdatedAt   int64
	ID          string
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, updateDevice,
		arg.Name,
		arg.Host,
		arg.PortsJson,
		arg.PortMapJson,
		arg.Username,
		arg.SecretEnc,
		arg.Kind,
		arg.Authorized,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
