// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diagnostics.sql

package db

import (
	"context"
)

const deleteCameraLogsBefore = `-- name: DeleteCameraLogsBefore :execrows
DELETE FROM camera_logs WHERE at < ?1
`

func (q *Queries) DeleteCameraLogsBefore(ctx context.Context, before int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCameraLogsBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCameraMetricsBefore = `-- name: DeleteCameraMetricsBefore :execrows
DELETE FROM camera_metrics WHERE resolution = ?1 AND at < ?2
`

type DeleteCameraMetricsBeforeParams struct {
	Resolution int64
	Before     int64
}

func (q *Queries) DeleteCameraMetricsBefore(ctx context.Context, arg DeleteCameraMetricsBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCameraMetricsBefore, arg.Resolution, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteConnectionStatsBefore = `-- name: DeleteConnectionStatsBefore :execrows
DELETE FROM connection_stats WHERE minute < ?1
`

func (q *Queries) DeleteConnectionStatsBefore(ctx context.Context, before int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteConnectionStatsBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteGapsBefore = `-- name: DeleteGapsBefore :execrows
DELETE FROM gaps WHERE last_at < ?1
`

func (q *Queries) DeleteGapsBefore(ctx context.Context, before int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGapsBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRequestStatsBefore = `-- name: DeleteRequestStatsBefore :execrows
DELETE FROM request_stats WHERE minute < ?1
`

func (q *Queries) DeleteRequestStatsBefore(ctx context.Context, before int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRequestStatsBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertCameraLog = `-- name: InsertCameraLog :exec
INSERT INTO camera_logs (camera_id, at, level, source, msg, attrs_json) VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type InsertCameraLogParams struct {
	CameraID  string
	At        int64
	Level     string
	Source    string
	Msg       string
	AttrsJson string
}

func (q *Queries) InsertCameraLog(ctx context.Context, arg InsertCameraLogParams) error {
	_, err := q.db.ExecContext(ctx, insertCameraLog,
		arg.CameraID,
		arg.At,
		arg.Level,
		arg.Source,
		arg.Msg,
		arg.AttrsJson,
	)
	return err
}

const insertCameraMetric = `-- name: InsertCameraMetric :exec
INSERT OR REPLACE INTO camera_metrics (camera_id, resolution, at, cpu_percent, rss_bytes, clients, bytes_in, bytes_out, requests)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type InsertCameraMetricParams struct {
	CameraID   string
	Resolution int64
	At         int64
	CpuPercent float64
	RssBytes   int64
	Clients    int64
	BytesIn    int64
	BytesOut   int64
	Requests   int64
}

func (q *Queries) InsertCameraMetric(ctx context.Context, arg InsertCameraMetricParams) error {
	_, err := q.db.ExecContext(ctx, insertCameraMetric,
		arg.CameraID,
		arg.Resolution,
		arg.At,
		arg.CpuPercent,
		arg.RssBytes,
		arg.Clients,
		arg.BytesIn,
		arg.BytesOut,
		arg.Requests,
	)
	return err
}

const listCameraIDs = `-- name: ListCameraIDs :many
SELECT id FROM cameras ORDER BY id
`

func (q *Queries) ListCameraIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCameraIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraLogs = `-- name: ListCameraLogs :many
SELECT id, camera_id, at, level, source, msg, attrs_json FROM camera_logs WHERE camera_id = ?1 AND id < ?2 ORDER BY id DESC LIMIT ?3
`

type ListCameraLogsParams struct {
	CameraID string
	Before   int64
	Lim      int64
}

func (q *Queries) ListCameraLogs(ctx context.Context, arg ListCameraLogsParams) ([]CameraLog, error) {
	rows, err := q.db.QueryContext(ctx, listCameraLogs, arg.CameraID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraLog{}
	for rows.Next() {
		var i CameraLog
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.At,
			&i.Level,
			&i.Source,
			&i.Msg,
			&i.AttrsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraMetrics = `-- name: ListCameraMetrics :many
SELECT camera_id, resolution, at, cpu_percent, rss_bytes, clients, bytes_in, bytes_out, requests FROM camera_metrics WHERE camera_id = ?1 AND resolution = ?2 AND at > ?3 ORDER BY at
`

type ListCameraMetricsParams struct {
	CameraID   string
	Resolution int64
	Since      int64
}

func (q *Queries) ListCameraMetrics(ctx context.Context, arg ListCameraMetricsParams) ([]CameraMetric, error) {
	rows, err := q.db.QueryContext(ctx, listCameraMetrics, arg.CameraID, arg.Resolution, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraMetric{}
	for rows.Next() {
		var i CameraMetric
		if err := rows.Scan(
			&i.CameraID,
			&i.Resolution,
			&i.At,
			&i.CpuPercent,
			&i.RssBytes,
			&i.Clients,
			&i.BytesIn,
			&i.BytesOut,
			&i.Requests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraStates = `-- name: ListCameraStates :many
SELECT cameras.id, cameras.name, COALESCE(camera_status.actual_state, 'stopped') AS state
FROM cameras LEFT JOIN camera_status ON camera_status.camera_id = cameras.id
ORDER BY cameras.name
`

type ListCameraStatesRow struct {
	ID    string
	Name  string
	State string
}

func (q *Queries) ListCameraStates(ctx context.Context) ([]ListCameraStatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCameraStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCameraStatesRow{}
	for rows.Next() {
		var i ListCameraStatesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionStats = `-- name: ListConnectionStats :many
SELECT camera_id, minute, protocol, client_ip, opened, closed, duration_ms, max_duration_ms FROM connection_stats WHERE camera_id = ?1 AND minute >= ?2 ORDER BY minute, protocol, client_ip
`

type ListConnectionStatsParams struct {
	CameraID string
	Since    int64
}

func (q *Queries) ListConnectionStats(ctx context.Context, arg ListConnectionStatsParams) ([]ConnectionStat, error) {
	rows, err := q.db.QueryContext(ctx, listConnectionStats, arg.CameraID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectionStat{}
	for rows.Next() {
		var i ConnectionStat
		if err := rows.Scan(
			&i.CameraID,
			&i.Minute,
			&i.Protocol,
			&i.ClientIp,
			&i.Opened,
			&i.Closed,
			&i.DurationMs,
			&i.MaxDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGaps = `-- name: ListGaps :many
SELECT camera_id, protocol, summary, client_ip, count, first_at, last_at FROM gaps WHERE camera_id = ?1 ORDER BY last_at DESC LIMIT 500
`

func (q *Queries) ListGaps(ctx context.Context, cameraID string) ([]Gap, error) {
	rows, err := q.db.QueryContext(ctx, listGaps, cameraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gap{}
	for rows.Next() {
		var i Gap
		if err := rows.Scan(
			&i.CameraID,
			&i.Protocol,
			&i.Summary,
			&i.ClientIp,
			&i.Count,
			&i.FirstAt,
			&i.LastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestStats = `-- name: ListRequestStats :many
SELECT camera_id, minute, client_ip, route, count, errors, auth_failures, p50_ms, p95_ms, max_ms, first_at, last_at FROM request_stats WHERE camera_id = ?1 AND minute >= ?2 ORDER BY minute, client_ip, route
`

type ListRequestStatsParams struct {
	CameraID string
	Since    int64
}

func (q *Queries) ListRequestStats(ctx context.Context, arg ListRequestStatsParams) ([]RequestStat, error) {
	rows, err := q.db.QueryContext(ctx, listRequestStats, arg.CameraID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestStat{}
	for rows.Next() {
		var i RequestStat
		if err := rows.Scan(
			&i.CameraID,
			&i.Minute,
			&i.ClientIp,
			&i.Route,
			&i.Count,
			&i.Errors,
			&i.AuthFailures,
			&i.P50Ms,
			&i.P95Ms,
			&i.MaxMs,
			&i.FirstAt,
			&i.LastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimCameraLogs = `-- name: TrimCameraLogs :execrows
DELETE FROM camera_logs WHERE camera_logs.camera_id = ?1 AND camera_logs.id <= (
  SELECT l.id FROM camera_logs AS l WHERE l.camera_id = ?1 ORDER BY l.id DESC LIMIT 1 OFFSET ?2)
`

type TrimCameraLogsParams struct {
	CameraID string
	Keep     int64
}

// Keeps the newest logs of a camera.
func (q *Queries) TrimCameraLogs(ctx context.Context, arg TrimCameraLogsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, trimCameraLogs, arg.CameraID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertConnectionStat = `-- name: UpsertConnectionStat :exec
INSERT INTO connection_stats (camera_id, minute, protocol, client_ip, opened, closed, duration_ms, max_duration_ms)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
ON CONFLICT (camera_id, minute, protocol, client_ip) DO UPDATE SET
  opened = connection_stats.opened + excluded.opened,
  closed = connection_stats.closed + excluded.closed,
  duration_ms = connection_stats.duration_ms + excluded.duration_ms,
  max_duration_ms = max(connection_stats.max_duration_ms, excluded.max_duration_ms)
`

type UpsertConnectionStatParams struct {
	CameraID      string
	Minute        int64
	Protocol      string
	ClientIp      string
	Opened        int64
	Closed        int64
	DurationMs    int64
	MaxDurationMs int64
}

func (q *Queries) UpsertConnectionStat(ctx context.Context, arg UpsertConnectionStatParams) error {
	_, err := q.db.ExecContext(ctx, upsertConnectionStat,
		arg.CameraID,
		arg.Minute,
		arg.Protocol,
		arg.ClientIp,
		arg.Opened,
		arg.Closed,
		arg.DurationMs,
		arg.MaxDurationMs,
	)
	return err
}

const upsertGap = `-- name: UpsertGap :exec
INSERT INTO gaps (camera_id, protocol, summary, client_ip, count, first_at, last_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?6)
ON CONFLICT (camera_id, protocol, summary, client_ip) DO UPDATE SET
  count = gaps.count + excluded.count,
  last_at = max(gaps.last_at, excluded.last_at)
`

type UpsertGapParams struct {
	CameraID string
	Protocol string
	Summary  string
	ClientIp string
	Count    int64
	At       int64
}

func (q *Queries) UpsertGap(ctx context.Context, arg UpsertGapParams) error {
	_, err := q.db.ExecContext(ctx, upsertGap,
		arg.CameraID,
		arg.Protocol,
		arg.Summary,
		arg.ClientIp,
		arg.Count,
		arg.At,
	)
	return err
}

const upsertRequestStat = `-- name: UpsertRequestStat :exec
INSERT INTO request_stats (camera_id, minute, client_ip, route, count, errors, auth_failures, p50_ms, p95_ms, max_ms, first_at, last_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
ON CONFLICT (camera_id, minute, client_ip, route) DO UPDATE SET
  p50_ms = (request_stats.p50_ms * request_stats.count + excluded.p50_ms * excluded.count) / (request_stats.count + excluded.count),
  count = request_stats.count + excluded.count,
  errors = request_stats.errors + excluded.errors,
  auth_failures = request_stats.auth_failures + excluded.auth_failures,
  p95_ms = max(request_stats.p95_ms, excluded.p95_ms),
  max_ms = max(request_stats.max_ms, excluded.max_ms),
  first_at = min(request_stats.first_at, excluded.first_at),
  last_at = max(request_stats.last_at, excluded.last_at)
`

type UpsertRequestStatParams struct {
	CameraID     string
	Minute       int64
	ClientIp     string
	Route        string
	Count        int64
	Errors       int64
	AuthFailures int64
	P50Ms        float64
	P95Ms        float64
	MaxMs        float64
	FirstAt      int64
	LastAt       int64
}

// Partial reports of the same minute add up; the median is weighted by
// the requests of each report and the 95th percentile is the highest.
func (q *Queries) UpsertRequestStat(ctx context.Context, arg UpsertRequestStatParams) error {
	_, err := q.db.ExecContext(ctx, upsertRequestStat,
		arg.CameraID,
		arg.Minute,
		arg.ClientIp,
		arg.Route,
		arg.Count,
		arg.Errors,
		arg.AuthFailures,
		arg.P50Ms,
		arg.P95Ms,
		arg.MaxMs,
		arg.FirstAt,
		arg.LastAt,
	)
	return err
}
