// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const deleteDeliveriesBefore = `-- name: DeleteDeliveriesBefore :execrows
DELETE FROM deliveries WHERE at < ?1
`

func (q *Queries) DeleteDeliveriesBefore(ctx context.Context, before int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeliveriesBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEventsBefore = `-- name: DeleteEventsBefore :execrows
DELETE FROM events WHERE at < ?1
`

func (q *Queries) DeleteEventsBefore(ctx context.Context, before int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEventsBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTarget = `-- name: DeleteTarget :execrows
DELETE FROM targets WHERE id = ?1
`

func (q *Queries) DeleteTarget(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTarget, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEvent = `-- name: GetEvent :one
SELECT events.id, events.camera_id, events.type, events.at, events.data_json, events.rule_id, events.trigger_id, cameras.name AS camera_name
FROM events
JOIN cameras ON cameras.id = events.camera_id
WHERE events.id = ?1
`

type GetEventRow struct {
	ID         string
	CameraID   string
	Type       string
	At         int64
	DataJson   string
	RuleID     sql.NullString
	TriggerID  sql.NullString
	CameraName string
}

func (q *Queries) GetEvent(ctx context.Context, id string) (GetEventRow, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i GetEventRow
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.Type,
		&i.At,
		&i.DataJson,
		&i.RuleID,
		&i.TriggerID,
		&i.CameraName,
	)
	return i, err
}

const getTarget = `-- name: GetTarget :one
SELECT id, name, type, config_json, secret_enc, enabled, created_at FROM targets WHERE id = ?1
`

func (q *Queries) GetTarget(ctx context.Context, id string) (Target, error) {
	row := q.db.QueryRowContext(ctx, getTarget, id)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ConfigJson,
		&i.SecretEnc,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :exec
INSERT INTO deliveries (id, event_id, target_id, attempt, at, status, http_status, latency_ms, error)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type InsertDeliveryParams struct {
	ID         string
	EventID    string
	TargetID   string
	Attempt    int64
	At         int64
	Status     string
	HttpStatus sql.NullInt64
	LatencyMs  sql.NullInt64
	Error      string
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, insertDelivery,
		arg.ID,
		arg.EventID,
		arg.TargetID,
		arg.Attempt,
		arg.At,
		arg.Status,
		arg.HttpStatus,
		arg.LatencyMs,
		arg.Error,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (id, camera_id, type, at, data_json, rule_id, trigger_id)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type InsertEventParams struct {
	ID        string
	CameraID  string
	Type      string
	At        int64
	DataJson  string
	RuleID    sql.NullString
	TriggerID sql.NullString
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.CameraID,
		arg.Type,
		arg.At,
		arg.DataJson,
		arg.RuleID,
		arg.TriggerID,
	)
	return err
}

const insertTarget = `-- name: InsertTarget :exec
INSERT INTO targets (id, name, type, config_json, secret_enc, enabled, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type InsertTargetParams struct {
	ID         string
	Name       string
	Type       string
	ConfigJson string
	SecretEnc  []byte
	Enabled    int64
	CreatedAt  int64
}

func (q *Queries) InsertTarget(ctx context.Context, arg InsertTargetParams) error {
	_, err := q.db.ExecContext(ctx, insertTarget,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.ConfigJson,
		arg.SecretEnc,
		arg.Enabled,
		arg.CreatedAt,
	)
	return err
}

const listDeliveriesForEvents = `-- name: ListDeliveriesForEvents :many
SELECT deliveries.id, deliveries.event_id, deliveries.target_id, deliveries.attempt, deliveries.at, deliveries.status, deliveries.http_status, deliveries.latency_ms, deliveries.error, coalesce(targets.name, '') AS target_name
FROM deliveries
LEFT JOIN targets ON targets.id = deliveries.target_id
WHERE deliveries.event_id IN (/*SLICE:event_ids*/?)
ORDER BY deliveries.event_id, deliveries.target_id, deliveries.attempt
`

type ListDeliveriesForEventsRow struct {
	ID         string
	EventID    string
	TargetID   string
	Attempt    int64
	At         int64
	Status     string
	HttpStatus sql.NullInt64
	LatencyMs  sql.NullInt64
	Error      string
	TargetName string
}

func (q *Queries) ListDeliveriesForEvents(ctx context.Context, eventIds []string) ([]ListDeliveriesForEventsRow, error) {
	query := listDeliveriesForEvents
	var queryParams []interface{}
	if len(eventIds) > 0 {
		for _, v := range eventIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:event_ids*/?", strings.Repeat(",?", len(eventIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:event_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveriesForEventsRow{}
	for rows.Next() {
		var i ListDeliveriesForEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TargetID,
			&i.Attempt,
			&i.At,
			&i.Status,
			&i.HttpStatus,
			&i.LatencyMs,
			&i.Error,
			&i.TargetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT events.id, events.camera_id, events.type, events.at, events.data_json, events.rule_id, events.trigger_id, cameras.name AS camera_name
FROM events
JOIN cameras ON cameras.id = events.camera_id
WHERE (CAST(?1 AS TEXT) = '' OR events.id < CAST(?1 AS TEXT))
  AND (CAST(?2 AS TEXT) = '' OR events.camera_id = CAST(?2 AS TEXT))
  AND (CAST(?3 AS TEXT) = '' OR events.type = CAST(?3 AS TEXT))
  AND (CAST(?4 AS TEXT) = '' OR EXISTS (
        SELECT 1 FROM deliveries WHERE deliveries.event_id = events.id AND deliveries.status = CAST(?4 AS TEXT)))
ORDER BY events.id DESC
LIMIT ?5
`

type ListEventsParams struct {
	Cursor   string
	CameraID string
	Type     string
	Delivery string
	Limit    int64
}

type ListEventsRow struct {
	ID         string
	CameraID   string
	Type       string
	At         int64
	DataJson   string
	RuleID     sql.NullString
	TriggerID  sql.NullString
	CameraName string
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEvents,
		arg.Cursor,
		arg.CameraID,
		arg.Type,
		arg.Delivery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Type,
			&i.At,
			&i.DataJson,
			&i.RuleID,
			&i.TriggerID,
			&i.CameraName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargets = `-- name: ListTargets :many
SELECT targets.id, targets.name, targets.type, targets.config_json, targets.secret_enc, targets.enabled, targets.created_at,
       (SELECT count(*) FROM camera_targets WHERE camera_targets.target_id = targets.id) AS camera_count
FROM targets
ORDER BY targets.name
`

type ListTargetsRow struct {
	ID          string
	Name        string
	Type        string
	ConfigJson  string
	SecretEnc   []byte
	Enabled     int64
	CreatedAt   int64
	CameraCount int64
}

func (q *Queries) ListTargets(ctx context.Context) ([]ListTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTargetsRow{}
	for rows.Next() {
		var i ListTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.ConfigJson,
			&i.SecretEnc,
			&i.Enabled,
			&i.CreatedAt,
			&i.CameraCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTarget = `-- name: UpdateTarget :exec
UPDATE targets SET name = ?1, config_json = ?2, secret_enc = ?3, enabled = ?4 WHERE id = ?5
`

type UpdateTargetParams struct {
	Name       string
	ConfigJson string
	SecretEnc  []byte
	Enabled    int64
	ID         string
}

func (q *Queries) UpdateTarget(ctx context.Context, arg UpdateTargetParams) error {
	_, err := q.db.ExecContext(ctx, updateTarget,
		arg.Name,
		arg.ConfigJson,
		arg.SecretEnc,
		arg.Enabled,
		arg.ID,
	)
	return err
}
