// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: faults.sql

package db

import (
	"context"
	"database/sql"
)

const deleteFaultsBefore = `-- name: DeleteFaultsBefore :execrows
DELETE FROM faults WHERE ended_at IS NOT NULL AND ended_at < ?1
`

func (q *Queries) DeleteFaultsBefore(ctx context.Context, before sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFaultsBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const endFault = `-- name: EndFault :execrows
UPDATE faults SET ended_at = ?1, ended_by = ?2 WHERE id = ?3 AND ended_at IS NULL
`

type EndFaultParams struct {
	EndedAt sql.NullInt64
	EndedBy string
	ID      string
}

func (q *Queries) EndFault(ctx context.Context, arg EndFaultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, endFault, arg.EndedAt, arg.EndedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFault = `-- name: GetFault :one
SELECT id, camera_id, kind, params_json, started_at, expires_at, ended_at, ended_by, created_by FROM faults WHERE id = ?1
`

func (q *Queries) GetFault(ctx context.Context, id string) (Fault, error) {
	row := q.db.QueryRowContext(ctx, getFault, id)
	var i Fault
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.Kind,
		&i.ParamsJson,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.EndedBy,
		&i.CreatedBy,
	)
	return i, err
}

const insertFault = `-- name: InsertFault :exec
INSERT INTO faults (id, camera_id, kind, params_json, started_at, expires_at, created_by)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type InsertFaultParams struct {
	ID         string
	CameraID   string
	Kind       string
	ParamsJson string
	StartedAt  int64
	ExpiresAt  sql.NullInt64
	CreatedBy  string
}

func (q *Queries) InsertFault(ctx context.Context, arg InsertFaultParams) error {
	_, err := q.db.ExecContext(ctx, insertFault,
		arg.ID,
		arg.CameraID,
		arg.Kind,
		arg.ParamsJson,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	return err
}

const listCameraFaults = `-- name: ListCameraFaults :many
SELECT id, camera_id, kind, params_json, started_at, expires_at, ended_at, ended_by, created_by FROM faults WHERE camera_id = ?1 ORDER BY started_at DESC LIMIT ?2
`

type ListCameraFaultsParams struct {
	CameraID string
	Limit    int64
}

func (q *Queries) ListCameraFaults(ctx context.Context, arg ListCameraFaultsParams) ([]Fault, error) {
	rows, err := q.db.QueryContext(ctx, listCameraFaults, arg.CameraID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fault{}
	for rows.Next() {
		var i Fault
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Kind,
			&i.ParamsJson,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.EndedAt,
			&i.EndedBy,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredFaults = `-- name: ListExpiredFaults :many
SELECT id, camera_id, kind, params_json, started_at, expires_at, ended_at, ended_by, created_by FROM faults WHERE ended_at IS NULL AND expires_at IS NOT NULL AND expires_at <= ?1
`

func (q *Queries) ListExpiredFaults(ctx context.Context, now sql.NullInt64) ([]Fault, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredFaults, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fault{}
	for rows.Next() {
		var i Fault
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Kind,
			&i.ParamsJson,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.EndedAt,
			&i.EndedBy,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenFaults = `-- name: ListOpenFaults :many
SELECT id, camera_id, kind, params_json, started_at, expires_at, ended_at, ended_by, created_by FROM faults WHERE ended_at IS NULL ORDER BY started_at
`

func (q *Queries) ListOpenFaults(ctx context.Context) ([]Fault, error) {
	rows, err := q.db.QueryContext(ctx, listOpenFaults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fault{}
	for rows.Next() {
		var i Fault
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Kind,
			&i.ParamsJson,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.EndedAt,
			&i.EndedBy,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
