// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
)

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = ?1
`

func (q *Queries) DeleteJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, type, title, status, progress, step, params_json, checkpoint_json, question_json, result_json, dedupe_key, created_by, created_at, started_at, finished_at, error FROM jobs WHERE id = ?1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Status,
		&i.Progress,
		&i.Step,
		&i.ParamsJson,
		&i.CheckpointJson,
		&i.QuestionJson,
		&i.ResultJson,
		&i.DedupeKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
	)
	return i, err
}

const getOpenJobByKey = `-- name: GetOpenJobByKey :one
SELECT id, type, title, status, progress, step, params_json, checkpoint_json, question_json, result_json, dedupe_key, created_by, created_at, started_at, finished_at, error FROM jobs
WHERE dedupe_key = ?1 AND status IN ('queued', 'running', 'waiting', 'interrupted')
`

func (q *Queries) GetOpenJobByKey(ctx context.Context, dedupeKey sql.NullString) (Job, error) {
	row := q.db.QueryRowContext(ctx, getOpenJobByKey, dedupeKey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Status,
		&i.Progress,
		&i.Step,
		&i.ParamsJson,
		&i.CheckpointJson,
		&i.QuestionJson,
		&i.ResultJson,
		&i.DedupeKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (id, type, title, status, params_json, dedupe_key, created_by, created_at)
VALUES (?1, ?2, ?3, 'queued', ?4, ?5, ?6, ?7)
`

type InsertJobParams struct {
	ID         string
	Type       string
	Title      string
	ParamsJson string
	DedupeKey  sql.NullString
	CreatedBy  string
	CreatedAt  int64
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.ExecContext(ctx, insertJob,
		arg.ID,
		arg.Type,
		arg.Title,
		arg.ParamsJson,
		arg.DedupeKey,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertJobEvent = `-- name: InsertJobEvent :exec
INSERT INTO job_events (job_id, seq, at, kind, payload_json)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertJobEventParams struct {
	JobID       string
	Seq         int64
	At          int64
	Kind        string
	PayloadJson string
}

func (q *Queries) InsertJobEvent(ctx context.Context, arg InsertJobEventParams) error {
	_, err := q.db.ExecContext(ctx, insertJobEvent,
		arg.JobID,
		arg.Seq,
		arg.At,
		arg.Kind,
		arg.PayloadJson,
	)
	return err
}

const listFinishedJobsBefore = `-- name: ListFinishedJobsBefore :many
SELECT id FROM jobs WHERE finished_at < ?1 AND status IN ('completed', 'failed', 'canceled')
`

func (q *Queries) ListFinishedJobsBefore(ctx context.Context, before sql.NullInt64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFinishedJobsBefore, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobEvents = `-- name: ListJobEvents :many
SELECT job_id, seq, at, kind, payload_json FROM job_events WHERE job_id = ?1 AND seq > ?2 ORDER BY seq LIMIT ?3
`

type ListJobEventsParams struct {
	JobID string
	After int64
	Limit int64
}

func (q *Queries) ListJobEvents(ctx context.Context, arg ListJobEventsParams) ([]JobEvent, error) {
	rows, err := q.db.QueryContext(ctx, listJobEvents, arg.JobID, arg.After, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobEvent{}
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.JobID,
			&i.Seq,
			&i.At,
			&i.Kind,
			&i.PayloadJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many

SELECT id, type, title, status, progress, step, params_json, checkpoint_json, question_json, result_json, dedupe_key, created_by, created_at, started_at, finished_at, error FROM jobs
WHERE (CAST(?1 AS TEXT) = '' OR id < CAST(?1 AS TEXT))
  AND (CAST(?2 AS TEXT) = '' OR type = CAST(?2 AS TEXT))
  AND (CAST(?3 AS TEXT) = ''
       OR status = CAST(?3 AS TEXT)
       OR (CAST(?3 AS TEXT) = 'active' AND status IN ('queued', 'running', 'waiting', 'interrupted'))
       OR (CAST(?3 AS TEXT) = 'finished' AND status IN ('completed', 'failed', 'canceled')))
ORDER BY id DESC
LIMIT ?4
`

type ListJobsParams struct {
	Cursor string
	Type   string
	Status string
	Limit  int64
}

// Active covers what still needs the node or the user: queued, running,
// waiting and interrupted jobs.
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs,
		arg.Cursor,
		arg.Type,
		arg.Status,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Status,
			&i.Progress,
			&i.Step,
			&i.ParamsJson,
			&i.CheckpointJson,
			&i.QuestionJson,
			&i.ResultJson,
			&i.DedupeKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT id, type, title, status, progress, step, params_json, checkpoint_json, question_json, result_json, dedupe_key, created_by, created_at, started_at, finished_at, error FROM jobs WHERE status = ?1 ORDER BY id LIMIT ?2
`

type ListJobsByStatusParams struct {
	Status string
	Limit  int64
}

func (q *Queries) ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Status,
			&i.Progress,
			&i.Step,
			&i.ParamsJson,
			&i.CheckpointJson,
			&i.QuestionJson,
			&i.ResultJson,
			&i.DedupeKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxJobEventSeq = `-- name: MaxJobEventSeq :one
SELECT CAST(coalesce(max(seq), 0) AS INTEGER) AS seq FROM job_events WHERE job_id = ?1
`

func (q *Queries) MaxJobEventSeq(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxJobEventSeq, jobID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const updateJob = `-- name: UpdateJob :exec
UPDATE jobs
SET status = ?1, progress = ?2, step = ?3, checkpoint_json = ?4,
    question_json = ?5, result_json = ?6, started_at = ?7,
    finished_at = ?8, error = ?9
WHERE id = ?10
`

type UpdateJobParams struct {
	Status         string
	Progress       float64
	Step           string
	CheckpointJson string
	QuestionJson   sql.NullString
	ResultJson     string
	StartedAt      sql.NullInt64
	FinishedAt     sql.NullInt64
	Error          string
	ID             string
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) error {
	_, err := q.db.ExecContext(ctx, updateJob,
		arg.Status,
		arg.Progress,
		arg.Step,
		arg.CheckpointJson,
		arg.QuestionJson,
		arg.ResultJson,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Error,
		arg.ID,
	)
	return err
}
