// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"
)

const deleteAsset = `-- name: DeleteAsset :execrows
DELETE FROM assets WHERE id = ?1
`

func (q *Queries) DeleteAsset(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAsset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAsset = `-- name: GetAsset :one
SELECT id, sha256, kind, mime, width, height, size, filename, builtin, created_at FROM assets WHERE id = ?1
`

func (q *Queries) GetAsset(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.Kind,
		&i.Mime,
		&i.Width,
		&i.Height,
		&i.Size,
		&i.Filename,
		&i.Builtin,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetBySHA256 = `-- name: GetAssetBySHA256 :one
SELECT id, sha256, kind, mime, width, height, size, filename, builtin, created_at FROM assets WHERE sha256 = ?1
`

func (q *Queries) GetAssetBySHA256(ctx context.Context, sha256 string) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAssetBySHA256, sha256)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.Kind,
		&i.Mime,
		&i.Width,
		&i.Height,
		&i.Size,
		&i.Filename,
		&i.Builtin,
		&i.CreatedAt,
	)
	return i, err
}

const getRendition = `-- name: GetRendition :one
SELECT id, asset_id, codec, width, height, fps, gop, bitrate, sha256, status, error, created_at FROM renditions WHERE id = ?1
`

func (q *Queries) GetRendition(ctx context.Context, id string) (Rendition, error) {
	row := q.db.QueryRowContext(ctx, getRendition, id)
	var i Rendition
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Codec,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.Gop,
		&i.Bitrate,
		&i.Sha256,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getRenditionByParams = `-- name: GetRenditionByParams :one
SELECT id, asset_id, codec, width, height, fps, gop, bitrate, sha256, status, error, created_at FROM renditions
WHERE asset_id = ?1 AND codec = ?2 AND width = ?3 AND height = ?4
  AND fps = ?5 AND gop = ?6 AND bitrate = ?7
`

type GetRenditionByParamsParams struct {
	AssetID string
	Codec   string
	Width   int64
	Height  int64
	Fps     int64
	Gop     int64
	Bitrate int64
}

func (q *Queries) GetRenditionByParams(ctx context.Context, arg GetRenditionByParamsParams) (Rendition, error) {
	row := q.db.QueryRowContext(ctx, getRenditionByParams,
		arg.AssetID,
		arg.Codec,
		arg.Width,
		arg.Height,
		arg.Fps,
		arg.Gop,
		arg.Bitrate,
	)
	var i Rendition
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Codec,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.Gop,
		&i.Bitrate,
		&i.Sha256,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const insertAsset = `-- name: InsertAsset :exec
INSERT INTO assets (id, sha256, kind, mime, width, height, size, filename, builtin, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
`

type InsertAssetParams struct {
	ID        string
	Sha256    string
	Kind      string
	Mime      string
	Width     int64
	Height    int64
	Size      int64
	Filename  string
	Builtin   int64
	CreatedAt int64
}

func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) error {
	_, err := q.db.ExecContext(ctx, insertAsset,
		arg.ID,
		arg.Sha256,
		arg.Kind,
		arg.Mime,
		arg.Width,
		arg.Height,
		arg.Size,
		arg.Filename,
		arg.Builtin,
		arg.CreatedAt,
	)
	return err
}

const insertRendition = `-- name: InsertRendition :exec
INSERT INTO renditions (id, asset_id, codec, width, height, fps, gop, bitrate, sha256, status, error, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, '', 'pending', '', ?9)
ON CONFLICT (asset_id, codec, width, height, fps, gop, bitrate) DO NOTHING
`

type InsertRenditionParams struct {
	ID        string
	AssetID   string
	Codec     string
	Width     int64
	Height    int64
	Fps       int64
	Gop       int64
	Bitrate   int64
	CreatedAt int64
}

func (q *Queries) InsertRendition(ctx context.Context, arg InsertRenditionParams) error {
	_, err := q.db.ExecContext(ctx, insertRendition,
		arg.ID,
		arg.AssetID,
		arg.Codec,
		arg.Width,
		arg.Height,
		arg.Fps,
		arg.Gop,
		arg.Bitrate,
		arg.CreatedAt,
	)
	return err
}

const listAssets = `-- name: ListAssets :many
SELECT assets.id, assets.sha256, assets.kind, assets.mime, assets.width, assets.height, assets.size, assets.filename, assets.builtin, assets.created_at,
       (SELECT count(*) FROM camera_streams WHERE camera_streams.asset_id = assets.id) AS camera_count
FROM assets
ORDER BY assets.builtin DESC, assets.created_at DESC
`

type ListAssetsRow struct {
	ID          string
	Sha256      string
	Kind        string
	Mime        string
	Width       int64
	Height      int64
	Size        int64
	Filename    string
	Builtin     int64
	CreatedAt   int64
	CameraCount int64
}

func (q *Queries) ListAssets(ctx context.Context) ([]ListAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetsRow{}
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.Kind,
			&i.Mime,
			&i.Width,
			&i.Height,
			&i.Size,
			&i.Filename,
			&i.Builtin,
			&i.CreatedAt,
			&i.CameraCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenditionsByStatus = `-- name: ListRenditionsByStatus :many
SELECT id, asset_id, codec, width, height, fps, gop, bitrate, sha256, status, error, created_at FROM renditions WHERE status = ?1 ORDER BY created_at
`

func (q *Queries) ListRenditionsByStatus(ctx context.Context, status string) ([]Rendition, error) {
	rows, err := q.db.QueryContext(ctx, listRenditionsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rendition{}
	for rows.Next() {
		var i Rendition
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.Codec,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.Gop,
			&i.Bitrate,
			&i.Sha256,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRenditionStatus = `-- name: SetRenditionStatus :exec
UPDATE renditions SET status = ?1, sha256 = ?2, error = ?3 WHERE id = ?4
`

type SetRenditionStatusParams struct {
	Status string
	Sha256 string
	Error  string
	ID     string
}

func (q *Queries) SetRenditionStatus(ctx context.Context, arg SetRenditionStatusParams) error {
	_, err := q.db.ExecContext(ctx, setRenditionStatus,
		arg.Status,
		arg.Sha256,
		arg.Error,
		arg.ID,
	)
	return err
}
