// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type ApiToken struct {
	ID         string
	UserID     string
	Name       string
	TokenHash  string
	Prefix     string
	ScopesJson string
	ExpiresAt  sql.NullInt64
	LastUsedAt sql.NullInt64
	LastUsedIp string
	CreatedAt  int64
}

type Asset struct {
	ID        string
	Sha256    string
	Kind      string
	Mime      string
	Width     int64
	Height    int64
	Size      int64
	Filename  string
	Builtin   int64
	CreatedAt int64
}

type AuditLog struct {
	ID         string
	At         int64
	ActorType  string
	ActorID    string
	Action     string
	EntityType string
	EntityID   string
	OriginIp   string
	DiffJson   string
	Origin     string
	ActorName  string
	TokenID    string
	TokenName  string
}

type Camera struct {
	ID             string
	Name           string
	ProfileID      string
	ProfileVersion string
	Serial         string
	DesiredState   string
	Autostart      int64
	TagsJson       string
	CreatedAt      int64
	UpdatedAt      int64
}

type CameraNetwork struct {
	CameraID string
	Mode     string
	ParentIf string
	Mac      string
	IpMode   string
	Ip       string
	Netmask  string
	Gateway  string
	DnsJson  string
}

type CameraProtocol struct {
	CameraID    string
	EngineKey   string
	Enabled     int64
	Port        int64
	OptionsJson string
}

type CameraState struct {
	CameraID  string
	Key       string
	ValueJson string
	Origin    string
	UpdatedAt int64
}

type CameraStatus struct {
	CameraID      string
	ActualState   string
	Reason        string
	StartedAt     sql.NullInt64
	LastHeartbeat sql.NullInt64
	UpdatedAt     int64
}

type CameraStream struct {
	CameraID    string
	Stream      string
	AssetID     string
	RenditionID sql.NullString
}

type CameraTarget struct {
	CameraID       string
	TargetID       string
	EventTypesJson string
	OverridesJson  string
}

type CameraUser struct {
	ID          string
	CameraID    string
	Username    string
	PasswordEnc []byte
	Role        string
}

type Delivery struct {
	ID         string
	EventID    string
	TargetID   string
	Attempt    int64
	At         int64
	Status     string
	HttpStatus sql.NullInt64
	LatencyMs  sql.NullInt64
	Error      string
}

type Event struct {
	ID        string
	CameraID  string
	Type      string
	At        int64
	DataJson  string
	RuleID    sql.NullString
	TriggerID sql.NullString
}

type Package struct {
	ID              string
	Kind            string
	PkgID           string
	Version         string
	Sha256          string
	SignatureStatus string
	Signer          string
	ManifestJson    string
	ReportJson      string
	Enabled         int64
	InstalledAt     int64
}

type Profile struct {
	ID           string
	PackageID    string
	ProfileID    string
	Version      string
	Name         string
	Vendor       string
	Model        string
	FirmwareJson string
	ResolvedJson string
	Level        string
	CoverageJson string
	Archived     int64
	CreatedAt    int64
}

type Rendition struct {
	ID        string
	AssetID   string
	Codec     string
	Width     int64
	Height    int64
	Fps       int64
	Gop       int64
	Bitrate   int64
	Sha256    string
	Status    string
	Error     string
	CreatedAt int64
}

type Session struct {
	ID        string
	UserID    string
	ExpiresAt int64
	Ip        string
	UserAgent string
	CreatedAt int64
}

type Setting struct {
	Key       string
	ValueJson string
}

type Target struct {
	ID         string
	Name       string
	Type       string
	ConfigJson string
	SecretEnc  []byte
	Enabled    int64
	CreatedAt  int64
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	Role         string
	Disabled     int64
	CreatedAt    int64
}
