// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package db

import (
	"context"
)

const deleteTrustedKey = `-- name: DeleteTrustedKey :execrows
DELETE FROM trusted_keys WHERE id = ?1
`

func (q *Queries) DeleteTrustedKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrustedKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPackage = `-- name: GetPackage :one
SELECT id, kind, pkg_id, version, sha256, signature_status, signer, manifest_json, report_json, enabled, installed_at, source FROM packages WHERE id = ?1
`

func (q *Queries) GetPackage(ctx context.Context, id string) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackage, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PkgID,
		&i.Version,
		&i.Sha256,
		&i.SignatureStatus,
		&i.Signer,
		&i.ManifestJson,
		&i.ReportJson,
		&i.Enabled,
		&i.InstalledAt,
		&i.Source,
	)
	return i, err
}

const getPackageByKey = `-- name: GetPackageByKey :one
SELECT id, kind, pkg_id, version, sha256, signature_status, signer, manifest_json, report_json, enabled, installed_at, source FROM packages WHERE kind = ?1 AND pkg_id = ?2 AND version = ?3
`

type GetPackageByKeyParams struct {
	Kind    string
	PkgID   string
	Version string
}

func (q *Queries) GetPackageByKey(ctx context.Context, arg GetPackageByKeyParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackageByKey, arg.Kind, arg.PkgID, arg.Version)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PkgID,
		&i.Version,
		&i.Sha256,
		&i.SignatureStatus,
		&i.Signer,
		&i.ManifestJson,
		&i.ReportJson,
		&i.Enabled,
		&i.InstalledAt,
		&i.Source,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, package_id, profile_id, version, name, vendor, model, firmware_json, resolved_json, level, coverage_json, archived, created_at, extends_ref FROM profiles WHERE id = ?1
`

func (q *Queries) GetProfile(ctx context.Context, id string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.ProfileID,
		&i.Version,
		&i.Name,
		&i.Vendor,
		&i.Model,
		&i.FirmwareJson,
		&i.ResolvedJson,
		&i.Level,
		&i.CoverageJson,
		&i.Archived,
		&i.CreatedAt,
		&i.ExtendsRef,
	)
	return i, err
}

const getProfileByRef = `-- name: GetProfileByRef :one
SELECT id, package_id, profile_id, version, name, vendor, model, firmware_json, resolved_json, level, coverage_json, archived, created_at, extends_ref FROM profiles WHERE profile_id = ?1 AND version = ?2
`

type GetProfileByRefParams struct {
	ProfileID string
	Version   string
}

func (q *Queries) GetProfileByRef(ctx context.Context, arg GetProfileByRefParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByRef, arg.ProfileID, arg.Version)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.ProfileID,
		&i.Version,
		&i.Name,
		&i.Vendor,
		&i.Model,
		&i.FirmwareJson,
		&i.ResolvedJson,
		&i.Level,
		&i.CoverageJson,
		&i.Archived,
		&i.CreatedAt,
		&i.ExtendsRef,
	)
	return i, err
}

const getTrustedKey = `-- name: GetTrustedKey :one
SELECT id, name, key_id, public_key, added_at FROM trusted_keys WHERE id = ?1
`

func (q *Queries) GetTrustedKey(ctx context.Context, id string) (TrustedKey, error) {
	row := q.db.QueryRowContext(ctx, getTrustedKey, id)
	var i TrustedKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyID,
		&i.PublicKey,
		&i.AddedAt,
	)
	return i, err
}

const insertPackage = `-- name: InsertPackage :exec
INSERT INTO packages (id, kind, pkg_id, version, sha256, signature_status, signer, manifest_json, report_json, enabled, installed_at, source)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
`

type InsertPackageParams struct {
	ID              string
	Kind            string
	PkgID           string
	Version         string
	Sha256          string
	SignatureStatus string
	Signer          string
	ManifestJson    string
	ReportJson      string
	Enabled         int64
	InstalledAt     int64
	Source          string
}

func (q *Queries) InsertPackage(ctx context.Context, arg InsertPackageParams) error {
	_, err := q.db.ExecContext(ctx, insertPackage,
		arg.ID,
		arg.Kind,
		arg.PkgID,
		arg.Version,
		arg.Sha256,
		arg.SignatureStatus,
		arg.Signer,
		arg.ManifestJson,
		arg.ReportJson,
		arg.Enabled,
		arg.InstalledAt,
		arg.Source,
	)
	return err
}

const insertProfile = `-- name: InsertProfile :exec
INSERT INTO profiles (id, package_id, profile_id, version, name, vendor, model, firmware_json, resolved_json, level, coverage_json, archived, created_at, extends_ref)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, 0, ?12, ?13)
`

type InsertProfileParams struct {
	ID           string
	PackageID    string
	ProfileID    string
	Version      string
	Name         string
	Vendor       string
	Model        string
	FirmwareJson string
	ResolvedJson string
	Level        string
	CoverageJson string
	CreatedAt    int64
	ExtendsRef   string
}

func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) error {
	_, err := q.db.ExecContext(ctx, insertProfile,
		arg.ID,
		arg.PackageID,
		arg.ProfileID,
		arg.Version,
		arg.Name,
		arg.Vendor,
		arg.Model,
		arg.FirmwareJson,
		arg.ResolvedJson,
		arg.Level,
		arg.CoverageJson,
		arg.CreatedAt,
		arg.ExtendsRef,
	)
	return err
}

const insertTrustedKey = `-- name: InsertTrustedKey :exec
INSERT INTO trusted_keys (id, name, key_id, public_key, added_at) VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertTrustedKeyParams struct {
	ID        string
	Name      string
	KeyID     string
	PublicKey string
	AddedAt   int64
}

func (q *Queries) InsertTrustedKey(ctx context.Context, arg InsertTrustedKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertTrustedKey,
		arg.ID,
		arg.Name,
		arg.KeyID,
		arg.PublicKey,
		arg.AddedAt,
	)
	return err
}

const listPackages = `-- name: ListPackages :many
SELECT id, kind, pkg_id, version, sha256, signature_status, signer, manifest_json, report_json, enabled, installed_at, source FROM packages ORDER BY installed_at DESC
`

func (q *Queries) ListPackages(ctx context.Context) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, listPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.PkgID,
			&i.Version,
			&i.Sha256,
			&i.SignatureStatus,
			&i.Signer,
			&i.ManifestJson,
			&i.ReportJson,
			&i.Enabled,
			&i.InstalledAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileVersions = `-- name: ListProfileVersions :many
SELECT id, package_id, profile_id, version, name, vendor, model, firmware_json, resolved_json, level, coverage_json, archived, created_at, extends_ref FROM profiles WHERE profile_id = ?1 ORDER BY created_at DESC
`

func (q *Queries) ListProfileVersions(ctx context.Context, profileID string) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfileVersions, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.ProfileID,
			&i.Version,
			&i.Name,
			&i.Vendor,
			&i.Model,
			&i.FirmwareJson,
			&i.ResolvedJson,
			&i.Level,
			&i.CoverageJson,
			&i.Archived,
			&i.CreatedAt,
			&i.ExtendsRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfiles = `-- name: ListProfiles :many
SELECT profiles.id, profiles.package_id, profiles.profile_id, profiles.version, profiles.name, profiles.vendor,
       profiles.model, profiles.firmware_json, profiles.level, profiles.coverage_json, profiles.archived,
       profiles.created_at, profiles.extends_ref, packages.signature_status, packages.signer, packages.source,
       (SELECT count(*) FROM cameras WHERE cameras.profile_id = profiles.profile_id AND cameras.profile_version = profiles.version) AS camera_count
FROM profiles
JOIN packages ON packages.id = profiles.package_id
ORDER BY profiles.profile_id, profiles.created_at DESC
`

type ListProfilesRow struct {
	ID              string
	PackageID       string
	ProfileID       string
	Version         string
	Name            string
	Vendor          string
	Model           string
	FirmwareJson    string
	Level           string
	CoverageJson    string
	Archived        int64
	CreatedAt       int64
	ExtendsRef      string
	SignatureStatus string
	Signer          string
	Source          string
	CameraCount     int64
}

func (q *Queries) ListProfiles(ctx context.Context) ([]ListProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfilesRow{}
	for rows.Next() {
		var i ListProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.ProfileID,
			&i.Version,
			&i.Name,
			&i.Vendor,
			&i.Model,
			&i.FirmwareJson,
			&i.Level,
			&i.CoverageJson,
			&i.Archived,
			&i.CreatedAt,
			&i.ExtendsRef,
			&i.SignatureStatus,
			&i.Signer,
			&i.Source,
			&i.CameraCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrustedKeys = `-- name: ListTrustedKeys :many
SELECT id, name, key_id, public_key, added_at FROM trusted_keys ORDER BY added_at
`

func (q *Queries) ListTrustedKeys(ctx context.Context) ([]TrustedKey, error) {
	rows, err := q.db.QueryContext(ctx, listTrustedKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrustedKey{}
	for rows.Next() {
		var i TrustedKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyID,
			&i.PublicKey,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProfileArchived = `-- name: SetProfileArchived :exec
UPDATE profiles SET archived = ?1 WHERE id = ?2
`

type SetProfileArchivedParams struct {
	Archived int64
	ID       string
}

func (q *Queries) SetProfileArchived(ctx context.Context, arg SetProfileArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setProfileArchived, arg.Archived, arg.ID)
	return err
}
