// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package db

import (
	"context"
)

const getPackage = `-- name: GetPackage :one
SELECT id, kind, pkg_id, version, sha256, signature_status, signer, manifest_json, report_json, enabled, installed_at FROM packages WHERE id = ?1
`

func (q *Queries) GetPackage(ctx context.Context, id string) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackage, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PkgID,
		&i.Version,
		&i.Sha256,
		&i.SignatureStatus,
		&i.Signer,
		&i.ManifestJson,
		&i.ReportJson,
		&i.Enabled,
		&i.InstalledAt,
	)
	return i, err
}

const getPackageByKey = `-- name: GetPackageByKey :one
SELECT id, kind, pkg_id, version, sha256, signature_status, signer, manifest_json, report_json, enabled, installed_at FROM packages WHERE kind = ?1 AND pkg_id = ?2 AND version = ?3
`

type GetPackageByKeyParams struct {
	Kind    string
	PkgID   string
	Version string
}

func (q *Queries) GetPackageByKey(ctx context.Context, arg GetPackageByKeyParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackageByKey, arg.Kind, arg.PkgID, arg.Version)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PkgID,
		&i.Version,
		&i.Sha256,
		&i.SignatureStatus,
		&i.Signer,
		&i.ManifestJson,
		&i.ReportJson,
		&i.Enabled,
		&i.InstalledAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, package_id, profile_id, version, name, vendor, model, firmware_json, resolved_json, level, coverage_json, archived, created_at FROM profiles WHERE id = ?1
`

func (q *Queries) GetProfile(ctx context.Context, id string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.ProfileID,
		&i.Version,
		&i.Name,
		&i.Vendor,
		&i.Model,
		&i.FirmwareJson,
		&i.ResolvedJson,
		&i.Level,
		&i.CoverageJson,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileByRef = `-- name: GetProfileByRef :one
SELECT id, package_id, profile_id, version, name, vendor, model, firmware_json, resolved_json, level, coverage_json, archived, created_at FROM profiles WHERE profile_id = ?1 AND version = ?2
`

type GetProfileByRefParams struct {
	ProfileID string
	Version   string
}

func (q *Queries) GetProfileByRef(ctx context.Context, arg GetProfileByRefParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByRef, arg.ProfileID, arg.Version)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.ProfileID,
		&i.Version,
		&i.Name,
		&i.Vendor,
		&i.Model,
		&i.FirmwareJson,
		&i.ResolvedJson,
		&i.Level,
		&i.CoverageJson,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const insertPackage = `-- name: InsertPackage :exec
INSERT INTO packages (id, kind, pkg_id, version, sha256, signature_status, signer, manifest_json, report_json, enabled, installed_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
`

type InsertPackageParams struct {
	ID              string
	Kind            string
	PkgID           string
	Version         string
	Sha256          string
	SignatureStatus string
	Signer          string
	ManifestJson    string
	ReportJson      string
	Enabled         int64
	InstalledAt     int64
}

func (q *Queries) InsertPackage(ctx context.Context, arg InsertPackageParams) error {
	_, err := q.db.ExecContext(ctx, insertPackage,
		arg.ID,
		arg.Kind,
		arg.PkgID,
		arg.Version,
		arg.Sha256,
		arg.SignatureStatus,
		arg.Signer,
		arg.ManifestJson,
		arg.ReportJson,
		arg.Enabled,
		arg.InstalledAt,
	)
	return err
}

const insertProfile = `-- name: InsertProfile :exec
INSERT INTO profiles (id, package_id, profile_id, version, name, vendor, model, firmware_json, resolved_json, level, coverage_json, archived, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, 0, ?12)
`

type InsertProfileParams struct {
	ID           string
	PackageID    string
	ProfileID    string
	Version      string
	Name         string
	Vendor       string
	Model        string
	FirmwareJson string
	ResolvedJson string
	Level        string
	CoverageJson string
	CreatedAt    int64
}

func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) error {
	_, err := q.db.ExecContext(ctx, insertProfile,
		arg.ID,
		arg.PackageID,
		arg.ProfileID,
		arg.Version,
		arg.Name,
		arg.Vendor,
		arg.Model,
		arg.FirmwareJson,
		arg.ResolvedJson,
		arg.Level,
		arg.CoverageJson,
		arg.CreatedAt,
	)
	return err
}

const listPackages = `-- name: ListPackages :many
SELECT id, kind, pkg_id, version, sha256, signature_status, signer, manifest_json, report_json, enabled, installed_at FROM packages ORDER BY installed_at DESC
`

func (q *Queries) ListPackages(ctx context.Context) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, listPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.PkgID,
			&i.Version,
			&i.Sha256,
			&i.SignatureStatus,
			&i.Signer,
			&i.ManifestJson,
			&i.ReportJson,
			&i.Enabled,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfiles = `-- name: ListProfiles :many
SELECT profiles.id, profiles.package_id, profiles.profile_id, profiles.version, profiles.name, profiles.vendor,
       profiles.model, profiles.firmware_json, profiles.level, profiles.coverage_json, profiles.archived,
       profiles.created_at, packages.signature_status,
       (SELECT count(*) FROM cameras WHERE cameras.profile_id = profiles.profile_id AND cameras.profile_version = profiles.version) AS camera_count
FROM profiles
JOIN packages ON packages.id = profiles.package_id
ORDER BY profiles.profile_id, profiles.created_at DESC
`

type ListProfilesRow struct {
	ID              string
	PackageID       string
	ProfileID       string
	Version         string
	Name            string
	Vendor          string
	Model           string
	FirmwareJson    string
	Level           string
	CoverageJson    string
	Archived        int64
	CreatedAt       int64
	SignatureStatus string
	CameraCount     int64
}

func (q *Queries) ListProfiles(ctx context.Context) ([]ListProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfilesRow{}
	for rows.Next() {
		var i ListProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.ProfileID,
			&i.Version,
			&i.Name,
			&i.Vendor,
			&i.Model,
			&i.FirmwareJson,
			&i.Level,
			&i.CoverageJson,
			&i.Archived,
			&i.CreatedAt,
			&i.SignatureStatus,
			&i.CameraCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProfileArchived = `-- name: SetProfileArchived :exec
UPDATE profiles SET archived = ?1 WHERE id = ?2
`

type SetProfileArchivedParams struct {
	Archived int64
	ID       string
}

func (q *Queries) SetProfileArchived(ctx context.Context, arg SetProfileArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setProfileArchived, arg.Archived, arg.ID)
	return err
}
