// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plugins.sql

package db

import (
	"context"
	"database/sql"
)

const disableEngine = `-- name: DisableEngine :exec
UPDATE plugins SET enabled = 0 WHERE engine = ?1 AND enabled = 1
`

func (q *Queries) DisableEngine(ctx context.Context, engine string) error {
	_, err := q.db.ExecContext(ctx, disableEngine, engine)
	return err
}

const disablePlugin = `-- name: DisablePlugin :execrows
UPDATE plugins SET enabled = 0 WHERE id = ?1 AND enabled = 1
`

func (q *Queries) DisablePlugin(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, disablePlugin, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enablePlugin = `-- name: EnablePlugin :exec
UPDATE plugins SET enabled = 1, approved_by = ?1, approved_at = ?2 WHERE id = ?3
`

type EnablePluginParams struct {
	ApprovedBy string
	ApprovedAt sql.NullInt64
	ID         string
}

func (q *Queries) EnablePlugin(ctx context.Context, arg EnablePluginParams) error {
	_, err := q.db.ExecContext(ctx, enablePlugin, arg.ApprovedBy, arg.ApprovedAt, arg.ID)
	return err
}

const getPlugin = `-- name: GetPlugin :one
SELECT plugins.id, plugins.package_id, plugins.engine, plugins.engine_version, plugins.executable, plugins.dir, plugins.permissions_json, plugins.descriptor_json, plugins.enabled, plugins.approved_by, plugins.approved_at, plugins.installed_at, packages.pkg_id, packages.signature_status, packages.signer, packages.sha256
FROM plugins JOIN packages ON packages.id = plugins.package_id
WHERE plugins.id = ?1
`

type GetPluginRow struct {
	ID              string
	PackageID       string
	Engine          string
	EngineVersion   string
	Executable      string
	Dir             string
	PermissionsJson string
	DescriptorJson  string
	Enabled         int64
	ApprovedBy      string
	ApprovedAt      sql.NullInt64
	InstalledAt     int64
	PkgID           string
	SignatureStatus string
	Signer          string
	Sha256          string
}

func (q *Queries) GetPlugin(ctx context.Context, id string) (GetPluginRow, error) {
	row := q.db.QueryRowContext(ctx, getPlugin, id)
	var i GetPluginRow
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Engine,
		&i.EngineVersion,
		&i.Executable,
		&i.Dir,
		&i.PermissionsJson,
		&i.DescriptorJson,
		&i.Enabled,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.InstalledAt,
		&i.PkgID,
		&i.SignatureStatus,
		&i.Signer,
		&i.Sha256,
	)
	return i, err
}

const getPluginByPackage = `-- name: GetPluginByPackage :one
SELECT id, package_id, engine, engine_version, executable, dir, permissions_json, descriptor_json, enabled, approved_by, approved_at, installed_at FROM plugins WHERE package_id = ?1
`

func (q *Queries) GetPluginByPackage(ctx context.Context, packageID string) (Plugin, error) {
	row := q.db.QueryRowContext(ctx, getPluginByPackage, packageID)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Engine,
		&i.EngineVersion,
		&i.Executable,
		&i.Dir,
		&i.PermissionsJson,
		&i.DescriptorJson,
		&i.Enabled,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.InstalledAt,
	)
	return i, err
}

const insertPlugin = `-- name: InsertPlugin :exec
INSERT INTO plugins (id, package_id, engine, engine_version, executable, dir, permissions_json, descriptor_json, installed_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type InsertPluginParams struct {
	ID              string
	PackageID       string
	Engine          string
	EngineVersion   string
	Executable      string
	Dir             string
	PermissionsJson string
	DescriptorJson  string
	InstalledAt     int64
}

func (q *Queries) InsertPlugin(ctx context.Context, arg InsertPluginParams) error {
	_, err := q.db.ExecContext(ctx, insertPlugin,
		arg.ID,
		arg.PackageID,
		arg.Engine,
		arg.EngineVersion,
		arg.Executable,
		arg.Dir,
		arg.PermissionsJson,
		arg.DescriptorJson,
		arg.InstalledAt,
	)
	return err
}

const listEnabledPlugins = `-- name: ListEnabledPlugins :many
SELECT id, package_id, engine, engine_version, executable, dir, permissions_json, descriptor_json, enabled, approved_by, approved_at, installed_at FROM plugins WHERE enabled = 1 ORDER BY engine
`

func (q *Queries) ListEnabledPlugins(ctx context.Context) ([]Plugin, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plugin{}
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.Engine,
			&i.EngineVersion,
			&i.Executable,
			&i.Dir,
			&i.PermissionsJson,
			&i.DescriptorJson,
			&i.Enabled,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlugins = `-- name: ListPlugins :many
SELECT plugins.id, plugins.package_id, plugins.engine, plugins.engine_version, plugins.executable, plugins.dir, plugins.permissions_json, plugins.descriptor_json, plugins.enabled, plugins.approved_by, plugins.approved_at, plugins.installed_at, packages.pkg_id, packages.signature_status, packages.signer, packages.sha256
FROM plugins JOIN packages ON packages.id = plugins.package_id
ORDER BY plugins.engine, plugins.installed_at DESC
`

type ListPluginsRow struct {
	ID              string
	PackageID       string
	Engine          string
	EngineVersion   string
	Executable      string
	Dir             string
	PermissionsJson string
	DescriptorJson  string
	Enabled         int64
	ApprovedBy      string
	ApprovedAt      sql.NullInt64
	InstalledAt     int64
	PkgID           string
	SignatureStatus string
	Signer          string
	Sha256          string
}

func (q *Queries) ListPlugins(ctx context.Context) ([]ListPluginsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPluginsRow{}
	for rows.Next() {
		var i ListPluginsRow
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.Engine,
			&i.EngineVersion,
			&i.Executable,
			&i.Dir,
			&i.PermissionsJson,
			&i.DescriptorJson,
			&i.Enabled,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.InstalledAt,
			&i.PkgID,
			&i.SignatureStatus,
			&i.Signer,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
