// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package db

import (
	"context"
)

const deleteCameraRecordings = `-- name: DeleteCameraRecordings :execrows
DELETE FROM recordings WHERE camera_id = ?1 AND location = ?2
`

type DeleteCameraRecordingsParams struct {
	CameraID string
	Location string
}

func (q *Queries) DeleteCameraRecordings(ctx context.Context, arg DeleteCameraRecordingsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCameraRecordings, arg.CameraID, arg.Location)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRecording = `-- name: DeleteRecording :exec
DELETE FROM recordings WHERE id = ?1
`

func (q *Queries) DeleteRecording(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRecording, id)
	return err
}

const findRecordings = `-- name: FindRecordings :many
SELECT id, camera_id, event_id, event_type, kind, stream, name, size, start_at, end_at, location, created_at FROM recordings
WHERE camera_id = ?1 AND location = ?2
  AND end_at >= ?3 AND start_at <= ?4
  AND (CAST(?5 AS TEXT) = '' OR kind = CAST(?5 AS TEXT))
  AND (CAST(?6 AS TEXT) = '' OR event_type = CAST(?6 AS TEXT))
ORDER BY start_at, name
LIMIT ?7
`

type FindRecordingsParams struct {
	CameraID  string
	Location  string
	FromAt    int64
	ToAt      int64
	Kind      string
	EventType string
	Limit     int64
}

func (q *Queries) FindRecordings(ctx context.Context, arg FindRecordingsParams) ([]Recording, error) {
	rows, err := q.db.QueryContext(ctx, findRecordings,
		arg.CameraID,
		arg.Location,
		arg.FromAt,
		arg.ToAt,
		arg.Kind,
		arg.EventType,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recording{}
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.EventID,
			&i.EventType,
			&i.Kind,
			&i.Stream,
			&i.Name,
			&i.Size,
			&i.StartAt,
			&i.EndAt,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCameraStorage = `-- name: GetCameraStorage :one
SELECT camera_id, kind, size_mb, overwrite, nas_url, nas_username, nas_secret_enc FROM camera_storage WHERE camera_id = ?1
`

func (q *Queries) GetCameraStorage(ctx context.Context, cameraID string) (CameraStorage, error) {
	row := q.db.QueryRowContext(ctx, getCameraStorage, cameraID)
	var i CameraStorage
	err := row.Scan(
		&i.CameraID,
		&i.Kind,
		&i.SizeMb,
		&i.Overwrite,
		&i.NasUrl,
		&i.NasUsername,
		&i.NasSecretEnc,
	)
	return i, err
}

const getRecording = `-- name: GetRecording :one
SELECT id, camera_id, event_id, event_type, kind, stream, name, size, start_at, end_at, location, created_at FROM recordings WHERE id = ?1
`

func (q *Queries) GetRecording(ctx context.Context, id string) (Recording, error) {
	row := q.db.QueryRowContext(ctx, getRecording, id)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.EventID,
		&i.EventType,
		&i.Kind,
		&i.Stream,
		&i.Name,
		&i.Size,
		&i.StartAt,
		&i.EndAt,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getRecordingByName = `-- name: GetRecordingByName :one
SELECT id, camera_id, event_id, event_type, kind, stream, name, size, start_at, end_at, location, created_at FROM recordings WHERE camera_id = ?1 AND location = ?2 AND name = ?3
`

type GetRecordingByNameParams struct {
	CameraID string
	Location string
	Name     string
}

func (q *Queries) GetRecordingByName(ctx context.Context, arg GetRecordingByNameParams) (Recording, error) {
	row := q.db.QueryRowContext(ctx, getRecordingByName, arg.CameraID, arg.Location, arg.Name)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.EventID,
		&i.EventType,
		&i.Kind,
		&i.Stream,
		&i.Name,
		&i.Size,
		&i.StartAt,
		&i.EndAt,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const insertRecording = `-- name: InsertRecording :exec
INSERT INTO recordings (id, camera_id, event_id, event_type, kind, stream, name, size, start_at, end_at, location, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
`

type InsertRecordingParams struct {
	ID        string
	CameraID  string
	EventID   string
	EventType string
	Kind      string
	Stream    string
	Name      string
	Size      int64
	StartAt   int64
	EndAt     int64
	Location  string
	CreatedAt int64
}

func (q *Queries) InsertRecording(ctx context.Context, arg InsertRecordingParams) error {
	_, err := q.db.ExecContext(ctx, insertRecording,
		arg.ID,
		arg.CameraID,
		arg.EventID,
		arg.EventType,
		arg.Kind,
		arg.Stream,
		arg.Name,
		arg.Size,
		arg.StartAt,
		arg.EndAt,
		arg.Location,
		arg.CreatedAt,
	)
	return err
}

const listCameraStorage = `-- name: ListCameraStorage :many
SELECT camera_id, kind, size_mb, overwrite, nas_url, nas_username, nas_secret_enc FROM camera_storage
`

func (q *Queries) ListCameraStorage(ctx context.Context) ([]CameraStorage, error) {
	rows, err := q.db.QueryContext(ctx, listCameraStorage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraStorage{}
	for rows.Next() {
		var i CameraStorage
		if err := rows.Scan(
			&i.CameraID,
			&i.Kind,
			&i.SizeMb,
			&i.Overwrite,
			&i.NasUrl,
			&i.NasUsername,
			&i.NasSecretEnc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNASHosts = `-- name: ListNASHosts :many
SELECT nas_url FROM camera_storage WHERE kind = 'nas'
`

func (q *Queries) ListNASHosts(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNASHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var nas_url string
		if err := rows.Scan(&nas_url); err != nil {
			return nil, err
		}
		items = append(items, nas_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordingsByEvent = `-- name: ListRecordingsByEvent :many
SELECT id, camera_id, event_id, event_type, kind, stream, name, size, start_at, end_at, location, created_at FROM recordings WHERE event_id = ?1 ORDER BY kind
`

func (q *Queries) ListRecordingsByEvent(ctx context.Context, eventID string) ([]Recording, error) {
	rows, err := q.db.QueryContext(ctx, listRecordingsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recording{}
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.EventID,
			&i.EventType,
			&i.Kind,
			&i.Stream,
			&i.Name,
			&i.Size,
			&i.StartAt,
			&i.EndAt,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestRecordings = `-- name: OldestRecordings :many
SELECT id, camera_id, event_id, event_type, kind, stream, name, size, start_at, end_at, location, created_at FROM recordings WHERE camera_id = ?1 AND location = ?2 ORDER BY start_at, name LIMIT ?3
`

type OldestRecordingsParams struct {
	CameraID string
	Location string
	Limit    int64
}

func (q *Queries) OldestRecordings(ctx context.Context, arg OldestRecordingsParams) ([]Recording, error) {
	rows, err := q.db.QueryContext(ctx, oldestRecordings, arg.CameraID, arg.Location, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recording{}
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.EventID,
			&i.EventType,
			&i.Kind,
			&i.Stream,
			&i.Name,
			&i.Size,
			&i.StartAt,
			&i.EndAt,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promisedSD = `-- name: PromisedSD :many
SELECT s.camera_id, s.size_mb, CAST(coalesce(sum(r.size), 0) AS INTEGER) AS used
FROM camera_storage s LEFT JOIN recordings r ON r.camera_id = s.camera_id AND r.location = 'sd'
WHERE s.kind = 'sd'
GROUP BY s.camera_id, s.size_mb
`

type PromisedSDRow struct {
	CameraID string
	SizeMb   int64
	Used     int64
}

func (q *Queries) PromisedSD(ctx context.Context) ([]PromisedSDRow, error) {
	rows, err := q.db.QueryContext(ctx, promisedSD)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromisedSDRow{}
	for rows.Next() {
		var i PromisedSDRow
		if err := rows.Scan(&i.CameraID, &i.SizeMb, &i.Used); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentRecordings = `-- name: RecentRecordings :many
SELECT id, camera_id, event_id, event_type, kind, stream, name, size, start_at, end_at, location, created_at FROM recordings
WHERE camera_id = ?1 AND location = ?2
  AND (CAST(?3 AS TEXT) = '' OR kind = CAST(?3 AS TEXT))
ORDER BY start_at DESC, name DESC
LIMIT ?4
`

type RecentRecordingsParams struct {
	CameraID string
	Location string
	Kind     string
	Limit    int64
}

func (q *Queries) RecentRecordings(ctx context.Context, arg RecentRecordingsParams) ([]Recording, error) {
	rows, err := q.db.QueryContext(ctx, recentRecordings,
		arg.CameraID,
		arg.Location,
		arg.Kind,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recording{}
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.EventID,
			&i.EventType,
			&i.Kind,
			&i.Stream,
			&i.Name,
			&i.Size,
			&i.StartAt,
			&i.EndAt,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordingUsage = `-- name: RecordingUsage :one
SELECT CAST(coalesce(sum(size), 0) AS INTEGER) AS used, count(*) AS files
FROM recordings WHERE camera_id = ?1 AND location = ?2
`

type RecordingUsageParams struct {
	CameraID string
	Location string
}

type RecordingUsageRow struct {
	Used  int64
	Files int64
}

func (q *Queries) RecordingUsage(ctx context.Context, arg RecordingUsageParams) (RecordingUsageRow, error) {
	row := q.db.QueryRowContext(ctx, recordingUsage, arg.CameraID, arg.Location)
	var i RecordingUsageRow
	err := row.Scan(&i.Used, &i.Files)
	return i, err
}

const upsertCameraStorage = `-- name: UpsertCameraStorage :exec
INSERT INTO camera_storage (camera_id, kind, size_mb, overwrite, nas_url, nas_username, nas_secret_enc)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT (camera_id) DO UPDATE SET kind = excluded.kind, size_mb = excluded.size_mb, overwrite = excluded.overwrite,
  nas_url = excluded.nas_url, nas_username = excluded.nas_username, nas_secret_enc = excluded.nas_secret_enc
`

type UpsertCameraStorageParams struct {
	CameraID     string
	Kind         string
	SizeMb       int64
	Overwrite    int64
	NasUrl       string
	NasUsername  string
	NasSecretEnc []byte
}

func (q *Queries) UpsertCameraStorage(ctx context.Context, arg UpsertCameraStorageParams) error {
	_, err := q.db.ExecContext(ctx, upsertCameraStorage,
		arg.CameraID,
		arg.Kind,
		arg.SizeMb,
		arg.Overwrite,
		arg.NasUrl,
		arg.NasUsername,
		arg.NasSecretEnc,
	)
	return err
}
