// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"
	"database/sql"
)

const createAPIToken = `-- name: CreateAPIToken :exec
INSERT INTO api_tokens (id, user_id, name, token_hash, prefix, scopes_json, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
`

type CreateAPITokenParams struct {
	ID         string
	UserID     string
	Name       string
	TokenHash  string
	Prefix     string
	ScopesJson string
	ExpiresAt  sql.NullInt64
	CreatedAt  int64
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, createAPIToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.ScopesJson,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteAPIToken = `-- name: DeleteAPIToken :execrows
DELETE FROM api_tokens WHERE id = ?1 AND user_id = ?2
`

type DeleteAPITokenParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAPIToken = `-- name: GetAPIToken :one
SELECT id, user_id, name, token_hash, prefix, scopes_json, expires_at, last_used_at, last_used_ip, created_at FROM api_tokens WHERE id = ?1 AND user_id = ?2
`

type GetAPITokenParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetAPIToken(ctx context.Context, arg GetAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPIToken, arg.ID, arg.UserID)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.ScopesJson,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.CreatedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT api_tokens.id, api_tokens.name, api_tokens.scopes_json, api_tokens.expires_at, api_tokens.last_used_at,
       users.id AS user_id, users.username, users.role, users.disabled
FROM api_tokens
JOIN users ON users.id = api_tokens.user_id
WHERE api_tokens.token_hash = ?1
`

type GetAPITokenByHashRow struct {
	ID         string
	Name       string
	ScopesJson string
	ExpiresAt  sql.NullInt64
	LastUsedAt sql.NullInt64
	UserID     string
	Username   string
	Role       string
	Disabled   int64
}

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i GetAPITokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ScopesJson,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.Disabled,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, user_id, name, token_hash, prefix, scopes_json, expires_at, last_used_at, last_used_ip, created_at FROM api_tokens WHERE user_id = ?1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAPITokens(ctx context.Context, userID string) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.ScopesJson,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = ?1, last_used_ip = ?2 WHERE id = ?3
`

type TouchAPITokenParams struct {
	LastUsedAt sql.NullInt64
	LastUsedIp string
	ID         string
}

func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, arg.LastUsedAt, arg.LastUsedIp, arg.ID)
	return err
}
