// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vca.sql

package db

import (
	"context"
)

const deleteCameraRules = `-- name: DeleteCameraRules :exec
DELETE FROM rules WHERE camera_id = ?1
`

func (q *Queries) DeleteCameraRules(ctx context.Context, cameraID string) error {
	_, err := q.db.ExecContext(ctx, deleteCameraRules, cameraID)
	return err
}

const deleteCameraTriggers = `-- name: DeleteCameraTriggers :exec
DELETE FROM triggers WHERE camera_id = ?1
`

func (q *Queries) DeleteCameraTriggers(ctx context.Context, cameraID string) error {
	_, err := q.db.ExecContext(ctx, deleteCameraTriggers, cameraID)
	return err
}

const insertRule = `-- name: InsertRule :exec
INSERT INTO rules (id, camera_id, position, name, type, geometry_json, params_json, enabled)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
`

type InsertRuleParams struct {
	ID           string
	CameraID     string
	Position     int64
	Name         string
	Type         string
	GeometryJson string
	ParamsJson   string
	Enabled      int64
}

func (q *Queries) InsertRule(ctx context.Context, arg InsertRuleParams) error {
	_, err := q.db.ExecContext(ctx, insertRule,
		arg.ID,
		arg.CameraID,
		arg.Position,
		arg.Name,
		arg.Type,
		arg.GeometryJson,
		arg.ParamsJson,
		arg.Enabled,
	)
	return err
}

const insertTrigger = `-- name: InsertTrigger :exec
INSERT INTO triggers (id, camera_id, position, name, type, params_json, enabled)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type InsertTriggerParams struct {
	ID         string
	CameraID   string
	Position   int64
	Name       string
	Type       string
	ParamsJson string
	Enabled    int64
}

func (q *Queries) InsertTrigger(ctx context.Context, arg InsertTriggerParams) error {
	_, err := q.db.ExecContext(ctx, insertTrigger,
		arg.ID,
		arg.CameraID,
		arg.Position,
		arg.Name,
		arg.Type,
		arg.ParamsJson,
		arg.Enabled,
	)
	return err
}

const listAllRules = `-- name: ListAllRules :many
SELECT id, camera_id, position, name, type, geometry_json, params_json, enabled FROM rules ORDER BY camera_id, position
`

func (q *Queries) ListAllRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listAllRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Position,
			&i.Name,
			&i.Type,
			&i.GeometryJson,
			&i.ParamsJson,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTriggers = `-- name: ListAllTriggers :many
SELECT id, camera_id, position, name, type, params_json, enabled FROM triggers ORDER BY camera_id, position
`

func (q *Queries) ListAllTriggers(ctx context.Context) ([]Trigger, error) {
	rows, err := q.db.QueryContext(ctx, listAllTriggers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trigger{}
	for rows.Next() {
		var i Trigger
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Position,
			&i.Name,
			&i.Type,
			&i.ParamsJson,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraRules = `-- name: ListCameraRules :many
SELECT id, camera_id, position, name, type, geometry_json, params_json, enabled FROM rules WHERE camera_id = ?1 ORDER BY position
`

func (q *Queries) ListCameraRules(ctx context.Context, cameraID string) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listCameraRules, cameraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Position,
			&i.Name,
			&i.Type,
			&i.GeometryJson,
			&i.ParamsJson,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraTriggers = `-- name: ListCameraTriggers :many
SELECT id, camera_id, position, name, type, params_json, enabled FROM triggers WHERE camera_id = ?1 ORDER BY position
`

func (q *Queries) ListCameraTriggers(ctx context.Context, cameraID string) ([]Trigger, error) {
	rows, err := q.db.QueryContext(ctx, listCameraTriggers, cameraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trigger{}
	for rows.Next() {
		var i Trigger
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Position,
			&i.Name,
			&i.Type,
			&i.ParamsJson,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
